.TH tool1 1   
.P 
.SH NAME
.P 
.B tool1 - A tool to Vestibulum lacinia arcu eget nulla.
.P 
.SH SYNOPSIS
.P 
.B tool1 noOptionsCommand 
.RI  " "
.I "argument list stuff"
.P 
.B tool1 noArgumentListFullOptions 
.RI  [  "-t"  |  "--target"  " "  "TARGET"  ] " " [  "--noshortparam"  ] " " [  "-l"  ] " " [  "-p"  |  "--noparam"  ] " " [  "-n"  " "  "NOLONG"  ] " " [  "--noshort"  " "  "NOSHORT"  ] " " [  "-a"  |  "--another"  " "  "ANOTHER"  ]  " "
.I ""
.P 
.B tool1 fullcommand1 
.RI  [  "-t"  |  "--target"  " "  "TARGET"  ] " " [  "--noshortparam"  ] " " [  "-l"  ] " " [  "-p"  |  "--noparam"  ] " " [  "-n"  " "  "NOLONG"  ] " " [  "--noshort"  " "  "NOSHORT"  ] " " [  "-a"  |  "--another"  " "  "ANOTHER"  ]  " "
.I "argument list stuff"
.P 
.SH DESCRIPTION
.P 
.PP Tool1 is a really great Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. 
.P 
.B tool1 noOptionsCommand
builds a native executable from specified source files
.P 
.B tool1 noArgumentListFullOptions
builds a native executable from specified source files
.P 
.B tool1 fullcommand1
builds a native executable from specified source files
.P 
.SH OPTIONS
.P 
.TP
.B  "-t"  ", "  "--target"  " "  "TARGET" 
Specifies target binary output type. EXE or DLL
.P 
.TP
.B  "--noshortparam" 
Specifies another aptent taciti sociosqu ad litora torquent per conubia nostra
.P 
.TP
.B  "-l" 
Specifies noparam nolong congue elementum. Morbi in ipsum sit amet pede facilisis laoreet
.P 
.TP
.B  "-p"  ", "  "--noparam" 
Specifies noparam metus vitae pharetra auctor, sem
.P 
.TP
.B  "-n"  " "  "NOLONG" 
Specifies nolong Nunc feugiat mi a tellus consequat 
.P 
.TP
.B  "--noshort"  " "  "NOSHORT" 
Specifies noshortNam nec ante. Sed lacinia, urna non tincidunt
.P 
.TP
.B  "-a"  ", "  "--another"  " "  "ANOTHER" 
Specifies another aptent taciti sociosqu ad litora torquent per conubia nostra
.P 
.TP
.B  "-t"  ", "  "--target"  " "  "TARGET" 
Specifies target binary output type. EXE or DLL
.P 
.TP
.B  "--noshortparam" 
Specifies another aptent taciti sociosqu ad litora torquent per conubia nostra
.P 
.TP
.B  "-l" 
Specifies noparam nolong congue elementum. Morbi in ipsum sit amet pede facilisis laoreet
.P 
.TP
.B  "-p"  ", "  "--noparam" 
Specifies noparam metus vitae pharetra auctor, sem
.P 
.TP
.B  "-n"  " "  "NOLONG" 
Specifies nolong Nunc feugiat mi a tellus consequat 
.P 
.TP
.B  "--noshort"  " "  "NOSHORT" 
Specifies noshortNam nec ante. Sed lacinia, urna non tincidunt
.P 
.TP
.B  "-a"  ", "  "--another"  " "  "ANOTHER" 
Specifies another aptent taciti sociosqu ad litora torquent per conubia nostra
.P 
.SH AUTHOR
.P 
.B "Test Author" " " 
.RI ( "testing@testing.com" )
.P 
.SH COPYRIGHT
.P 
.B "This is the copyright of tool1."
