// <auto-generated />
namespace Microsoft.AspNetCore.StaticFiles
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Microsoft.AspNetCore.StaticFiles.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        /// No formatter provided.
        /// </summary>
        internal static string Args_NoFormatter
        {
            get { return GetString("Args_NoFormatter"); }
        }

        /// <summary>
        /// No formatter provided.
        /// </summary>
        internal static string FormatArgs_NoFormatter()
        {
            return GetString("Args_NoFormatter");
        }

        /// <summary>
        /// Index of
        /// </summary>
        internal static string HtmlDir_IndexOf
        {
            get { return GetString("HtmlDir_IndexOf"); }
        }

        /// <summary>
        /// Index of
        /// </summary>
        internal static string FormatHtmlDir_IndexOf()
        {
            return GetString("HtmlDir_IndexOf");
        }

        /// <summary>
        /// Last Modified
        /// </summary>
        internal static string HtmlDir_LastModified
        {
            get { return GetString("HtmlDir_LastModified"); }
        }

        /// <summary>
        /// Last Modified
        /// </summary>
        internal static string FormatHtmlDir_LastModified()
        {
            return GetString("HtmlDir_LastModified");
        }

        /// <summary>
        /// Modified
        /// </summary>
        internal static string HtmlDir_Modified
        {
            get { return GetString("HtmlDir_Modified"); }
        }

        /// <summary>
        /// Modified
        /// </summary>
        internal static string FormatHtmlDir_Modified()
        {
            return GetString("HtmlDir_Modified");
        }

        /// <summary>
        /// Name
        /// </summary>
        internal static string HtmlDir_Name
        {
            get { return GetString("HtmlDir_Name"); }
        }

        /// <summary>
        /// Name
        /// </summary>
        internal static string FormatHtmlDir_Name()
        {
            return GetString("HtmlDir_Name");
        }

        /// <summary>
        /// Size
        /// </summary>
        internal static string HtmlDir_Size
        {
            get { return GetString("HtmlDir_Size"); }
        }

        /// <summary>
        /// Size
        /// </summary>
        internal static string FormatHtmlDir_Size()
        {
            return GetString("HtmlDir_Size");
        }

        /// <summary>
        /// The list of files in the given directory.  Column headers are listed in the first row.
        /// </summary>
        internal static string HtmlDir_TableSummary
        {
            get { return GetString("HtmlDir_TableSummary"); }
        }

        /// <summary>
        /// The list of files in the given directory.  Column headers are listed in the first row.
        /// </summary>
        internal static string FormatHtmlDir_TableSummary()
        {
            return GetString("HtmlDir_TableSummary");
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
