#!/bin/sh
LC_ALL=C

# Stash unstaged changes
git stash -q --keep-index

# Select files to format
FILES=$(git diff --cached --name-only --pretty="")
[ -z "$FILES" ] && exit 0

# Format all selected files with dotnet-format
echo "dotnet-format: Formatting changed source files.."
echo "$FILES" | cat | xargs | sed -e 's/ /,/g' | xargs dotnet-format --folder . --include >/dev/null
echo "dotnet-format: $(git diff --cached --numstat | wc -l) file(s) formatted."

# Add files to staging
echo "$FILES" | xargs git add

# Restore unstaged changes
git stash pop -q

exit 0
