@Company.WebApplication1_HostAddress = http://localhost:5000

GET {{Company.WebApplication1_HostAddress}}/todos/
Accept: application/json

###

GET {{Company.WebApplication1_HostAddress}}/todos/1
Accept: application/json

###
