<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Proto\httpbody.proto" GrpcServices="Both" />
    <Protobuf Include="Proto\transcoding.proto" GrpcServices="Both" />

    <Protobuf Include="Proto\Issue045270\hello.proto" GrpcServices="Both" />
    <Protobuf Include="Proto\Issue045270\country.proto" GrpcServices="Both" />
    <Protobuf Include="Proto\Issue047349\message.proto" GrpcServices="Both" />    
    <Protobuf Include="Proto\Issue048192\hello.proto" GrpcServices="Both" />
    <Protobuf Include="Proto\Issue048192\customhttp.proto" GrpcServices="Both" />
    <Protobuf Include="Proto\Issue048192\customannotations.proto" GrpcServices="Both" />

    <Compile Include="..\Shared\TestGrpcServiceActivator.cs" Link="Infrastructure\TestGrpcServiceActivator.cs" />

    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />

    <ProjectReference Include="$(RepoRoot)src\Grpc\JsonTranscoding\src\Microsoft.AspNetCore.Grpc.JsonTranscoding\Microsoft.AspNetCore.Grpc.JsonTranscoding.csproj" />
  </ItemGroup>
</Project>
