<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <Nullable>enable</Nullable>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <NoWarn>$(NoWarn);NU1511</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.AspNetCore.Components" />
    <Reference Include="Microsoft.AspNetCore.Components.Endpoints" />
    <Reference Include="Microsoft.AspNetCore.Components.Platform" />
    <Reference Include="Microsoft.AspNetCore.Components.Server" />
    <Reference Include="Microsoft.AspNetCore.Components.Web" />
    <Reference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <Reference Include="Microsoft.AspNetCore.Hosting" />
    <Reference Include="Microsoft.AspNetCore.Http" />
    <Reference Include="Microsoft.AspNetCore.Routing" />
    <Reference Include="Microsoft.AspNetCore.Server.Kestrel" />
    <Reference Include="Microsoft.AspNetCore.StaticAssets" />
    <Reference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../PlatformTestApp.Client/PlatformTestApp.Client.csproj" />
  </ItemGroup>

</Project>
