# This configuration builds the repository and runs benchmarks

# Don't run CI for this config
trigger: none

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Windows_Build
    jobDisplayName: "Build only : Windows"
    agentOs: Windows
    buildArgs: -all -pack
    artifacts:
      path: artifacts/
      publish: true
      force: true
