#
# See https://learn.microsoft.com/azure/devops/pipelines/yaml-schema for details on this file.
#

trigger: none
pr: none

variables:
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: true
- name: EXECUTE_COMPONENTS_E2E_TESTS
  value: true
- name: _TeamName
  value:  AspNetCore
- name: PUPPETEER_SKIP_DOWNLOAD
  value: 1
- template: /eng/common/templates/variables/pool-providers.yml

jobs:
# CoreCLR runtime E2E tests (UseMonoRuntime=false)
- template: jobs/components-e2e-test-job.yml
  parameters:
    runtimeName: CoreCLR
    runtimeBuildArgs: '/p:UseMonoRuntime=false'
    buildRestoreArgs: ''

# Mono runtime (default) E2E tests
- template: jobs/components-e2e-test-job.yml
  parameters:
    runtimeName: Mono
