#
# See https://learn.microsoft.com/azure/devops/pipelines/yaml-schema for details on this file.
#

# Configure which branches trigger builds
trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
    - internal/release/*

# Run PR validation on all branches
pr:
  autoCancel: true
  branches:
    include:
    - '*'
  paths:
    include:
    - eng/*
    - src/Components/*
    - src/Extensions/*
    - src/Framework/*
    - src/Hosting/*
    - src/Http/*
    - src/Middleware/HttpLogging/*
    - src/Middleware/HttpOverrides/*
    - src/Middleware/HttpsPolicy/*
    - src/Middleware/Localization/*
    - src/Middleware/Session/*
    - src/Middleware/StaticFiles/*
    - src/Middleware/WebSockets/*
    - src/Servers/*
    - src/SignalR/*
    - src/Validation/*
    exclude:
    - '**/*.md'

variables:
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: true
- name: EXECUTE_COMPONENTS_E2E_TESTS
  value: true
- name: _TeamName
  value:  AspNetCore
- name: PUPPETEER_SKIP_DOWNLOAD
  value: 1
- template: /eng/common/templates/variables/pool-providers.yml

jobs:
# CoreCLR runtime E2E tests (UseMonoRuntime=false)
- template: jobs/components-e2e-test-job.yml
  parameters:
    runtimeName: CoreCLR
    runtimeBuildArgs: '/p:UseMonoRuntime=false'
    buildRestoreArgs: ''
    minimumTestCount: 500

# Mono runtime (default) E2E tests
- template: jobs/components-e2e-test-job.yml
  parameters:
    runtimeName: Mono
    minimumTestCount: 1000
