#
# See https://learn.microsoft.com/azure/devops/pipelines/yaml-schema for details on this file.
#

# Configure which branches trigger builds
trigger: none

pr:
  autoCancel: true
  branches:
    include:
    - '*'
  paths:
    include:
    - eng/*
    - src/Components/*
    - src/Extensions/*
    - src/Framework/*
    - src/Hosting/*
    - src/Http/*
    - src/Middleware/HttpLogging/*
    - src/Middleware/HttpOverrides/*
    - src/Middleware/HttpsPolicy/*
    - src/Middleware/Localization/*
    - src/Middleware/Session/*
    - src/Middleware/StaticFiles/*
    - src/Middleware/WebSockets/*
    - src/Servers/*
    - src/SignalR/*
    exclude:
    - '**/*.md'

variables:
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: true
- name: EXECUTE_COMPONENTS_E2E_TESTS
  value: true
- name: _TeamName
  value:  AspNetCore
- template: /eng/common/templates-official/variables/pool-providers.yml@self

resources:
  repositories:
  # Repo: 1ESPipelineTemplates/1ESPipelineTemplates
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Svc-Internal
        image: windows.vs2022.amd64
        os: windows
    stages:
    - stage: test
      displayName: Test
      jobs:
      - template: .azure/pipelines/jobs/components-e2e-test-job.yml@self
