#
# See https://learn.microsoft.com/azure/devops/pipelines/yaml-schema for details on this file.
#

# Configure which branches trigger builds
trigger: none

# no PR builds
pr: none

variables:
- template: /eng/common/templates/variables/pool-providers.yml

stages:
- stage: build_components
  displayName: Build Components
  jobs:
  # Build components on Windows (x64)
  - template: jobs/default-build.yml
    parameters:
      jobName: Windows_build
      jobDisplayName: "Build: Components"
      agentOs: Windows
      steps:
      - script: ./eng/build.cmd
                -ci
                -prepareMachine
                -arch x64
                /bl:$(Build.SourcesDirectory)/artifacts/log/build.components.x64.binlog
        displayName: Build x64
        workingDirectory: ./src/Components
      artifacts:
      - name: Windows_Logs
        path: artifacts/log/
        publishOnError: true
        includeForks: true

- stage: build_servers
  displayName: Build Servers
  jobs:
  # Build servers on Windows (x64)
  - template: jobs/default-build.yml
    parameters:
      jobName: Windows_build
      jobDisplayName: "Build: Servers"
      agentOs: Windows
      steps:
      - script: ./eng/build.cmd
                -ci
                -prepareMachine
                -arch x64
                /bl:$(Build.SourcesDirectory)/artifacts/log/build.servers.x64.binlog
        displayName: Build x64
        workingDirectory: ./src/Servers
      artifacts:
      - name: Windows_Logs
        path: artifacts/log/
        publishOnError: true
        includeForks: true

- stage: build_project_templates
  displayName: Build Project Templates
  jobs:
  # Build servers on Windows (x64)
  - template: jobs/default-build.yml
    parameters:
      jobName: Windows_build
      jobDisplayName: "Build: Project Templates"
      agentOs: Windows
      steps:
      - script: ./eng/build.cmd
                -ci
                -prepareMachine
                -arch x64
                /bl:$(Build.SourcesDirectory)/artifacts/log/build.projectTemplates.x64.binlog
        displayName: Build x64
        workingDirectory: ./src/ProjectTemplates
      artifacts:
      - name: Windows_Logs
        path: artifacts/log/
        publishOnError: true
        includeForks: true

- stage: build_all
  displayName: Build Everything
  jobs:
  # Build servers on Windows (x64)
  - template: jobs/default-build.yml
    parameters:
      jobName: Windows_build
      jobDisplayName: "Build: Everything"
      agentOs: Windows
      steps:
      - script: ./eng/build.cmd
                -ci
                -prepareMachine
                -arch x64
                /bl:$(Build.SourcesDirectory)/artifacts/log/build.all.x64.binlog
        displayName: Build x64
      artifacts:
      - name: Windows_Logs
        path: artifacts/log/
        publishOnError: true
        includeForks: true
