#
# See https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema for details on this file.
#

# Configure which branches trigger builds
trigger: none

stages:
- stage: build_components
  displayName: Build Components
  jobs:
  # Build components on Windows (x64)
  - template: jobs/default-build.yml
    parameters:
      codeSign: false
      jobName: Windows_build
      jobDisplayName: "Build: Components"
      agentOs: Windows
      steps:
      - script: git submodule init
      - script: git submodule update --recursive
      - script: cd ./src/Components
      - script: ./build.cmd
                -ci
                -arch x64
                /bl:artifacts/log/build.x64.binlog
        displayName: Build x64
      artifacts:
      - name: Windows_Logs
        path: artifacts/log/
        publishOnError: true
        includeForks: true

- stage: build_servers
  displayName: Build Servers
  jobs:
  # Build servers on Windows (x64)
  - template: jobs/default-build.yml
    parameters:
      codeSign: false
      jobName: Windows_build
      jobDisplayName: "Build: Servers"
      agentOs: Windows
      steps:
      - script: git submodule init
      - script: git submodule update --recursive
      - script: cd ./src/Servers
      - script: ./build.cmd
                -ci
                -arch x64
                /bl:artifacts/log/build.x64.binlog
        displayName: Build x64
      artifacts:
      - name: Windows_Logs
        path: artifacts/log/
        publishOnError: true
        includeForks: true
