
trigger:
- master
- release/*

jobs:
- template: jobs/default-build.yml
  parameters:
    agentOs: Windows
    jobName: Windows_FastCheck
    buildArgs: "/t:FastCheck"
    artifacts:
      publish: false
- template: jobs/default-build.yml
  parameters:
    agentOs: Windows
    jobName: Compile_Windows
    buildArgs: "/p:SkipTests=true"
    artifacts:
      publish: false
- job: RepoBuilds
  pool:
    vmImage: vs2017-win2016
  strategy:
    maxParallel: 3
    matrix:
      DataProtection:
        _FolderName: DataProtection
      WebSockets:
        _FolderName: WebSockets
  steps:
  - script: src/$(_FolderName)/build.cmd -ci
    displayName: Run src/$(_FolderName)/build.cmd
  - task: PublishTestResults@2
    displayName: Publish test results
    condition: always()
    inputs:
      testRunner: vstest
      testResultsFiles: 'src/$(_FolderName)/artifacts/logs/**/*.trx'
- template: jobs/iisintegration-job.yml
  parameters:
    TestGroupName: IIS
    SkipIISTests: false
    SkipIISExpressTests: true
    SkipIISForwardsCompatibilityTests: true
    SkipIISBackwardsCompatibilityTests: true
- template: jobs/iisintegration-job.yml
  parameters:
    TestGroupName: IISExpress
    SkipIISTests: true
    SkipIISExpressTests: false
    SkipIISForwardsCompatibilityTests: true
    SkipIISBackwardsCompatibilityTests: true
- template: jobs/iisintegration-job.yml
  parameters:
    TestGroupName: IISForwardCompat
    SkipIISTests: true
    SkipIISExpressTests: true
    SkipIISForwardsCompatibilityTests: false
    SkipIISBackwardsCompatibilityTests: true
- template: jobs/iisintegration-job.yml
  parameters:
    TestGroupName: IISBackCompat
    SkipIISTests: true
    SkipIISExpressTests: true
    SkipIISForwardsCompatibilityTests: true
    SkipIISBackwardsCompatibilityTests: false
