# Don't run CI for this config yet. We're not ready to move official builds on to Azure Pipelines
trigger: none

# Run PR validation on all branches
pr:
  branches:
    include:
    - '*'

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Helix_x64
    jobDisplayName: 'Tests: Helix x64'
    agentOs: Windows
    timeoutInMinutes: 240
    steps:
    - script: .\restore.cmd -ci
      displayName: Restore
    - script: .\build.cmd -ci -NoRestore -test -projects eng\helix\helix.proj /p:IsHelixJob=true /p:BuildAllProjects=true /p:BuildNative=true -bl
      displayName: Run build.cmd helix target
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken) # We need to set this env var to publish helix results to Azure Dev Ops
    artifacts:
    - name: Helix_logs
      path: artifacts/log/
      publishOnError: true

# Build Helix ARM64
- template: jobs/default-build.yml
  parameters:
    jobName: Helix_arm64
    jobDisplayName: "Tests: Helix ARM64"
    agentOs: Linux
    timeoutInMinutes: 240
    steps:
    - script: ./restore.sh -ci
      displayName: Restore
    - script: ./build.sh -ci --arch arm64 -test --no-build-nodejs -projects $(Build.SourcesDirectory)/eng/helix/helix.proj /p:IsHelixJob=true /p:BuildAllProjects=true /p:BuildNative=true -bl
      displayName: Run build.sh helix arm64 target
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken) # We need to set this env var to publish helix results to Azure Dev Ops
    installNodeJs: false
    artifacts:
    - name: Helix_arm64_logs
      path: artifacts/log/
      publishOnError: true
