# We only want to run full helix matrix on main
pr: none
trigger: none
schedules:
# Cron timezone is UTC.
- cron: "0 */12 * * *"
  branches:
    include:
    - main
  always: true
- cron: "0 9 * * *"
  branches:
    include:
    - release/5.0
    - release/6.0
  always: false

variables:
- name: _UseHelixOpenQueues
  value: ${{ ne(variables['System.TeamProject'], 'internal') }}
- ${{ if eq(variables['System.TeamProject'], 'internal') }}:
  - group: DotNet-HelixApi-Access

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Helix_matrix
    jobDisplayName: 'Tests: Helix full matrix'
    agentOs: Windows
    timeoutInMinutes: 480
    steps:
    - script: ./eng/build.cmd -ci -nobl -test -pack -arch x64 -all
              -projects eng\helix\helix.proj /p:IsHelixJob=true
              /p:CrossgenOutput=false /p:ASPNETCORE_TEST_LOG_DIR=artifacts/log
      displayName: Build and run Helix tests
      env:
        HelixApiAccessToken: $(HelixApiAccessToken) # Needed for internal queues
        SYSTEM_ACCESSTOKEN: $(System.AccessToken) # We need to set this env var to publish helix results to Azure Dev Ops
    artifacts:
    - name: Helix_logs
      path: artifacts/log/
      publishOnError: true
