# We want to run quarantined tests on master as well as on PRs
trigger:
  batch: true
  branches:
    include:
    - master

# Run PR validation on all branches
pr:
  branches:
    include:
    - '*'

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Helix_quarantine_x64
    jobDisplayName: 'Tests: Helix Quarantine x64'
    agentOs: Windows
    timeoutInMinutes: 240
    steps:
    - script: .\restore.cmd -ci
      displayName: Restore
    - script: .\build.cmd -ci -NoRestore -test -projects eng\helix\helix.proj /p:RunQuarantinedTests=true /p:IsRequiredCheck=true /p:IsHelixJob=true /p:BuildAllProjects=true /p:BuildNative=true /p:ASPNETCORE_TEST_LOG_DIR=artifacts/log -bl
      displayName: Run build.cmd helix target
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken) # We need to set this env var to publish helix results to Azure Dev Ops
    artifacts:
    - name: Helix_logs
      path: artifacts/log/
      publishOnError: true
