#
# See https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema for details on this file.
#

# Configure which branches trigger builds
# We want to run quarantined tests on release/5.0 and main as well as on PRs
trigger:
  batch: true
  branches:
    include:
    - main
    - release/5.0
    - release/6.0

# Run PR validation on branches that include Helix tests
pr:
  autoCancel: true
  branches:
    include:
    - main
    - release/5.0
  paths:
    exclude:
    - .github/*
    - .vscode/*
    - '**/*.md'
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

schedules:
- cron: "0 */4 * * *"
  displayName: Every 4 hours test run
  branches:
    include:
    - main
  always: true

variables:
- name: _UseHelixOpenQueues
  value: ${{ ne(variables['System.TeamProject'], 'internal') }}
- ${{ if eq(variables['System.TeamProject'], 'internal') }}:
  - group: DotNet-HelixApi-Access

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Helix_quarantined_x64
    jobDisplayName: 'Tests: Helix x64'
    agentOs: Windows
    timeoutInMinutes: 120
    steps:
    # Don't build Java projects because tests there cannot be quarantined and nothing else depends on them.
    - script: ./eng/build.cmd -ci -nobl -test -pack -arch x64 -all -noBuildJava
              -projects eng\helix\helix.proj /p:IsHelixPRCheck=true /p:RunQuarantinedTests=true /p:IsHelixJob=true
              /p:CrossgenOutput=false /p:ASPNETCORE_TEST_LOG_DIR=artifacts/log
      displayName: Build and run quarantined Helix tests
      continueOnError: true
      env:
        HelixApiAccessToken: $(HelixApiAccessToken) # Needed for internal queues
        SYSTEM_ACCESSTOKEN: $(System.AccessToken) # We need to set this env var to publish helix results to Azure Dev Ops
    artifacts:
    - name: Helix_logs
      path: artifacts/log/
      publishOnError: true

- template: jobs/default-build.yml
  parameters:
    jobName: Windows_Quarantined_x64
    jobDisplayName: 'Tests: Windows x64'
    agentOs: Windows
    timeoutInMinutes: 90
    isAzDOTestingJob: true
    enablePublishTestResults: false
    steps:
    # Don't build Java projects because tests there cannot be quarantined and nothing else depends on them.
    - script: ./eng/build.cmd -ci -nobl -test -pack -arch x64 -all -noBuildJava
        /p:RunQuarantinedTests=true /p:SkipHelixReadyTests=true
      displayName: Build and run Quarantined Tests
      continueOnError: true
    - task: PublishTestResults@2
      displayName: Publish Quarantined Test Results
      inputs:
        testResultsFormat: 'xUnit'
        testResultsFiles: '*.xml'
        searchFolder: '$(Build.SourcesDirectory)/artifacts/TestResults/$(_BuildConfig)/Quarantined'
        testRunTitle: Quarantine-$(AgentOsName)-$(BuildConfiguration)-xunit
        mergeTestResults: true
      condition: always()
    artifacts:
    - name: Windows_Quarantined_Test_Logs
      path: artifacts/log/
      publishOnError: true
      includeForks: true
    - name: Windows_Quarantined_Test_Results
      path: artifacts/TestResults/
      publishOnError: true
      includeForks: true

- template: jobs/default-build.yml
  parameters:
    jobName: MacOS_Quarantined_Test
    jobDisplayName: "Tests: macOS"
    agentOs: macOS
    timeoutInMinutes: 120
    isAzDOTestingJob: true
    enablePublishTestResults: false
    steps:
    # Don't build Java projects because tests there cannot be quarantined and nothing else depends on them.
    - bash: ./eng/build.sh --ci --nobl --test --pack -arch x64 --all --no-build-java
        -p:RunQuarantinedTests=true -p:SkipHelixReadyTests=true
      displayName: Build and run Quarantined Tests
      continueOnError: true
    - task: PublishTestResults@2
      displayName: Publish Quarantined Test Results
      inputs:
        testResultsFormat: 'xUnit'
        testResultsFiles: '*.xml'
        searchFolder: '$(Build.SourcesDirectory)/artifacts/TestResults/$(_BuildConfig)/Quarantined'
        testRunTitle: Quarantine-$(AgentOsName)-$(BuildConfiguration)-xunit
        mergeTestResults: true
      condition: always()
    artifacts:
    - name: MacOS_Quarantined_Test_Logs
      path: artifacts/log/
      publishOnError: true
      includeForks: true
    - name: MacOS_Quarantined_Test_Results
      path: artifacts/TestResults/
      publishOnError: true
      includeForks: true

- template: jobs/default-build.yml
  parameters:
    jobName: Linux_Quarantined_Test
    jobDisplayName: "Tests: Ubuntu x64"
    agentOs: Linux
    timeoutInMinutes: 60
    isAzDOTestingJob: true
    enablePublishTestResults: false
    useHostedUbuntu: false
    steps:
    # Don't build Java projects because tests there cannot be quarantined and nothing else depends on them.
    - bash: ./eng/build.sh --ci --nobl --test --pack -arch x64 --all --no-build-java
        -p:RunQuarantinedTests=true -p:SkipHelixReadyTests=true
      displayName: Build and run Quarantined Tests
      continueOnError: true
    - task: PublishTestResults@2
      displayName: Publish Quarantined Test Results
      inputs:
        testResultsFormat: 'xUnit'
        testResultsFiles: '*.xml'
        searchFolder: '$(Build.SourcesDirectory)/artifacts/TestResults/$(_BuildConfig)/Quarantined'
        testRunTitle: Quarantine-$(AgentOsName)-$(BuildConfiguration)-xunit
        mergeTestResults: true
      condition: always()
    artifacts:
    - name: Linux_Quarantined_Test_Logs
      path: artifacts/log/
      publishOnError: true
      includeForks: true
    - name: Linux_Quarantined_Test_Results
      path: artifacts/TestResults/
      publishOnError: true
      includeForks: true
