# We want to run quarantined tests on master as well as on PRs
trigger:
  batch: true
  branches:
    include:
    - master

schedules:
- cron: "0 */4 * * *"
  displayName: Every 4 hours test run
  branches:
    include:
    - master
  always: true

variables:
- ${{ if ne(variables['System.TeamProject'], 'internal') }}:
  - name: _UseHelixOpenQueues
    value: 'true'
- ${{ if eq(variables['System.TeamProject'], 'internal') }}:
  - group: DotNet-HelixApi-Access
  - name: _UseHelixOpenQueues
    value: 'false'

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Helix_quarantine_x64
    jobDisplayName: 'Tests: Helix Quarantine x64'
    agentOs: Windows
    timeoutInMinutes: 240
    steps:
    # Build the shared framework
    - script: ./build.cmd -ci -all -pack -arch x64 -buildNative /p:ASPNETCORE_TEST_LOG_DIR=artifacts/log /bl:artifacts/log/helix.build.x64.binlog
      displayName: Build shared fx
    - script: .\restore.cmd -ci
      displayName: Restore
    - script: .\build.cmd -ci -NoRestore -test -noBuildJava -projects eng\helix\helix.proj /p:RunQuarantinedTests=true /p:IsRequiredCheck=true /p:IsHelixJob=true /p:BuildAllProjects=true /p:BuildNative=true /p:RunTemplateTests=true /p:ASPNETCORE_TEST_LOG_DIR=artifacts/log -bl
      displayName: Run build.cmd helix target
      env:
        HelixApiAccessToken: $(HelixApiAccessToken) # Needed for internal queues
        SYSTEM_ACCESSTOKEN: $(System.AccessToken) # We need to set this env var to publish helix results to Azure Dev Ops
    artifacts:
    - name: Helix_logs
      path: artifacts/log/
      publishOnError: true
