# Only run this on PRs
trigger: none
# Run for all branches, only on paths that no-op other jobs
pr:
  autoCancel: true
  branches:
    include:
    - '*'
  paths:
    include:
    - .devcontainer/*
    - .github/*
    - .vscode/*
    - docs/*
    - '**/*.md'
    - LICENSE.TXT
    - THIRD-PARTY-NOTICES.TXT

# ABG - Always Be Green
jobs:
- template: /eng/common/templates/jobs/jobs.yml
  parameters:
    enableTelemetry: true
    helixRepo: dotnet/aspnetcore
    jobs:
    - job: Report_Green
      enableSBOM: false
      pool:
        name: $(DncEngPublicBuildPool)
        demands: ImageOverride -equals 1es-windows-2022
      steps:
      - powershell: |
          exit 0
        displayName: Exit 0