#
# See https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema for details on this file.
#

# Configure which branches trigger builds
trigger:
  branches:
    include:
    - main
    - release/*

# Do not run this pipeline for PR validation.
pr: none

variables:
- name: _BuildArgs
  value: '/p:SkipTestBuild=true'
- name: WindowsNonX64LogArgs
  value: -ExcludeCIBinaryLog

stages:
- stage: build
  displayName: Build
  jobs:
  # Build Windows (x64/x86/arm64)
  - template: jobs/default-build.yml
    parameters:
      jobName: Windows_build
      jobDisplayName: "Build: Windows x64/x86/arm64"
      enableRichCodeNavigation: true
      agentOs: Windows
      steps:
      - script: ./eng/build.cmd
                -ci
                -arch x64
                -all
                /p:EnableRichCodeNavigation=true
                $(_BuildArgs)
        displayName: Build x64

      # Build the x86 shared framework
      # This is going to actually build x86 native assets.
      - script: ./eng/build.cmd
                -ci
                -noBuildRepoTasks
                -arch x86
                -all
                -noBuildJava
                -noBuildNative
                /p:EnableRichCodeNavigation=true
                /p:OnlyPackPlatformSpecificPackages=true
                $(_BuildArgs)
                $(WindowsNonX64LogArgs)
        displayName: Build x86

      # Build the arm64 shared framework
      - script: ./eng/build.cmd
                -ci
                -noBuildRepoTasks
                -arch arm64
                -noBuildJava
                -noBuildNative
                /p:EnableRichCodeNavigation=true
                /p:OnlyPackPlatformSpecificPackages=true
                $(_BuildArgs)
                $(WindowsNonX64LogArgs)
        displayName: Build ARM64

      # Windows installers bundle x86/x64/arm64 assets
      - script: ./eng/build.cmd
                -ci
                -noBuildRepoTasks
                -buildInstallers
                -noBuildNative
                /p:EnableRichCodeNavigation=true
                $(_BuildArgs)
                $(WindowsNonX64LogArgs)
        displayName: Build Installers
