#
# See https://learn.microsoft.com/azure/devops/pipelines/yaml-schema for details on this file.
#

# Configure which branches trigger builds
trigger:
  branches:
    include:
    - main
    - release/*

# Do not run this pipeline for PR validation.
pr: none

variables:
- name: _BuildArgs
  value: '/p:SkipTestBuild=true'
- name: WindowsNonX64LogArgs
  value: -ExcludeCIBinaryLog
- template: /eng/common/templates/variables/pool-providers.yml

stages:
- stage: build
  displayName: Build
  jobs:
  # Build Windows (x64/x86/arm64)
  - template: jobs/default-build.yml
    parameters:
      jobName: Windows_build
      jobDisplayName: "Build: Windows x64/x86/arm64"
      enableRichCodeNavigation: true
      agentOs: Windows
      steps:
      - script: ./eng/build.cmd
                -ci
                -prepareMachine
                -nativeToolsOnMachine
                -arch x64
                -buildNative
                /p:EnableRichCodeNavigation=false
                $(_BuildArgs)
        displayName: Build x64 native assets

      - script: ./eng/build.cmd
                -ci
                -prepareMachine
                -nativeToolsOnMachine
                -arch x64
                -all
                -noBuildNative
                -noBuildRepoTasks
                $(_BuildArgs)
        displayName: Build x64

      # Build the x86 shared framework
      # This is going to actually build x86 native assets.
      - script: ./eng/build.cmd
                -ci
                -prepareMachine
                -nativeToolsOnMachine
                -arch x86
                -all
                -noBuildJava
                -noBuildNodeJS
                -noBuildNative
                -noBuildRepoTasks
                $(_BuildArgs)
                $(WindowsNonX64LogArgs)
        displayName: Build x86

      # Build the arm64 shared framework
      - script: ./eng/build.cmd
                -ci
                -prepareMachine
                -nativeToolsOnMachine
                -arch arm64
                -noBuildJava
                -noBuildNodeJS
                -noBuildNative
                -noBuildRepoTasks
                $(_BuildArgs)
                $(WindowsNonX64LogArgs)
        displayName: Build ARM64

