# Uses Scheduled Triggers, which aren't supported in YAML yet.
# https://learn.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=yaml#scheduled

# Daily Tests for ASP.NET Core SignalR
# These use Sauce Labs resources, hence they run daily rather than per-commit.

variables:
  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - group: DotNet-MSRC-Storage
    - group: AzureDevOps-Artifact-Feeds-Pats
  - template: /eng/common/templates/variables/pool-providers.yml

# The only Daily Tests we have run in Sauce Labs and only need to run on one machine (because they just trigger SauceLabs)
# Hence we use the 'default-build.yml' template because it represents a single phase
jobs:
- template: jobs/default-build.yml
  parameters:
    buildDirectory: src/SignalR
    buildArgs: "/p:DailyTests=true /p:SauceUser='$(asplab-sauce-labs-username)' /p:SauceKey='$(asplab-sauce-labs-access-key)' -t"
    agentOs: Windows
    jobName: SignalRDailyTests
    jobDisplayName: "SignalR Daily Tests"
    artifacts:
    - name: Windows_Logs
      path: artifacts/log/
      publishOnError: true
