# This configuration builds the repository and runs stress
pr: none

# Don't run CI for this config
trigger: none

variables:
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: true
- name: _TeamName
  value:  AspNetCore
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - name: _BuildArgs
    value: /p:TeamName=$(_TeamName)
      /p:OfficialBuildId=$(Build.BuildNumber)
- ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
  - name: _BuildArgs
    value: ''
- template: /eng/common/templates/variables/pool-providers.yml

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Windows_Stress_Test
    jobDisplayName: "Windows Stress test"
    agentOs: Windows
    isAzDOTestingJob: true
    steps:
    - script: .\src\Servers\Kestrel\stress\build.cmd -ci -prepareMachine -c Release
      displayName: Build Repo
    - script: .\.dotnet\dotnet.exe run --project .\src\Servers\Kestrel\stress\HttpStress.csproj -c Release -aspnetlog
      displayName: Run stress
    artifacts:
    - name: Windows_Test_Stress_Logs
      path: artifacts/log/
      publishOnError: true
