# Configure which branches trigger builds
# We want to run template tests on release/8.0 and later as well as on certain PRs
trigger:
  batch: true
  branches:
    include:
    - main
    - release/*

# Run PR validation on branches that include Helix tests
pr:
  autoCancel: true
  branches:
    include:
    - main
    - release/*
  paths:
    include:
    - src/ProjectTemplates/*
    - src/Components/*
    - src/Mvc/*

variables:
- name: _UseHelixOpenQueues
  value: ${{ ne(variables['System.TeamProject'], 'internal') }}
- ${{ if eq(variables['System.TeamProject'], 'internal') }}:
  - group: DotNet-HelixApi-Access
- template: /eng/common/templates/variables/pool-providers.yml

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Helix_templates_x64
    jobDisplayName: 'Tests: Helix template tests x64'
    agentOs: Windows
    timeoutInMinutes: 180
    steps:
    - script: git submodule update --init
      displayName: Update submodules
    # Build the shared framework
    - script: ./eng/build.cmd -ci -prepareMachine -nativeToolsOnMachine -nobl -all -pack -arch x64
              /p:CrossgenOutput=false /p:ASPNETCORE_TEST_LOG_DIR=artifacts/log /p:VsTestUseMSBuildOutput=false
      displayName: Build shared fx
    # -noBuildRepoTasks -noBuildNative -noBuild to avoid repeating work done in the previous step.
    - script: ./eng/build.cmd -ci -prepareMachine -nativeToolsOnMachine -all -noBuildRepoTasks -noBuildNative -noBuild -test
              -projects eng\helix\helix.proj /p:IsHelixPRCheck=true /p:IsHelixJob=true
              /p:CrossgenOutput=false /p:ASPNETCORE_TEST_LOG_DIR=artifacts/log
              /p:VsTestUseMSBuildOutput=false /p:OnlyTestProjectTemplates=true
      displayName: Run build.cmd helix target
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken) # We need to set this env var to publish helix results to Azure Dev Ops
    artifacts:
    - name: Helix_logs
      path: artifacts/log/
      publishOnError: true
