<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <OutputType>Exe</OutputType>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TieredCompilation>false</TieredCompilation>
    <DefineConstants>$(DefineConstants);IS_BENCHMARKS</DefineConstants>
    <SkipMicrobenchmarksValidation>true</SkipMicrobenchmarksValidation>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />

    <ProjectReference Include="$(RepoRoot)src\Servers\HttpSys\src\Microsoft.AspNetCore.Server.HttpSys.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="$(SharedSourceRoot)BenchmarkRunner\*.cs" />
  </ItemGroup>

</Project>
