# Folders
artifacts/
bin/
obj/
.dotnet/
.nuget/
.packages/
.tools/
.vs/
node_modules/
BenchmarkDotNet.Artifacts/
.gradle/
src/SignalR/clients/**/dist/
modules/
.ionide/

# File extensions
*.aps
*.binlog
*.dll
*.DS_Store
*.exe
*.idb
*.lib
*.log
*.pch
*.pdb
*.pidb
*.psess
*.res
*.snk
*.so
*.suo
*.svclog
*.tlog
*.user
*.userprefs
*.vspx

# Specific files, typically generated by tools
.config/dotnet-tools.json
msbuild.ProjectImports.zip
StyleCop.Cache
UpgradeLog.htm
.idea
mono_crash.*.json
mono_crash.*.blob
