<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DisablePackageReferenceRestrictions>true</DisablePackageReferenceRestrictions>
    <EnablePublicApiAnalyzer>false</EnablePublicApiAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" Version="9.4.0" />
  </ItemGroup>
</Project>
