<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <TestGroupName>IIS.FunctionalTests</TestGroupName>
    <DefineConstants>IIS_FUNCTIONALS</DefineConstants>
    <DisableFastUpToDateCheck>True</DisableFastUpToDateCheck>
    <SkipTests Condition=" '$(SkipIISTests)' == 'true' ">true</SkipTests>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!-- Required for System.Net.Quic which has a preview API in .NET 7 -->
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <!-- Required because 8.0.0 SDK no longer considers net7.0 the current TFM. -->
    <GenerateRequiresPreviewFeaturesAttribute>true</GenerateRequiresPreviewFeaturesAttribute>
  </PropertyGroup>

  <Import Project="../FunctionalTest.props" />

  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)src\Http\Routing.Abstractions\src\Microsoft.AspNetCore.Routing.Abstractions.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Http\Routing\src\Microsoft.AspNetCore.Routing.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Servers\HttpSys\src\Microsoft.AspNetCore.Server.HttpSys.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Servers\IIS\IIS\test\testassets\IIS.Common.TestLib\IIS.Common.TestLib.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Servers\IIS\IIS\test\testassets\InProcessWebSite\InProcessWebSite.csproj"
      Private="false"
      ReferenceOutputAssembly="false"
      SkipGetTargetFrameworkProperties="true" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Common.FunctionalTests\**\*.cs" />
    <Compile Include="..\IIS.Shared.FunctionalTests\**\*.cs" />
    <Compile Include="$(SharedSourceRoot)Http2cat\**\*.cs" LinkBase="Shared\Http2cat" />
    <Compile Include="$(SharedSourceRoot)runtime\Http2\**\*.cs" LinkBase="Shared\Http2\" />
    <Compile Include="$(SharedSourceRoot)runtime\IHttpStreamHeadersHandler.cs" LinkBase="Shared\IHttpStreamHeadersHandler.cs" />
    <Compile Include="$(SharedSourceRoot)Hpack\Obsoletions.cs" LinkBase="Shared\Obsoletions.cs" />
    <Compile Include="$(SharedSourceRoot)runtime\SR.cs" LinkBase="Shared\SR.cs" />
    <Compile Include="$(SharedSourceRoot)ServerInfrastructure\**\*.cs" LinkBase="Shared\" Exclude="$(SharedSourceRoot)ServerInfrastructure\DuplexPipe.cs" />
    <Compile Include="$(SharedSourceRoot)ValueTaskExtensions\**\*.cs" LinkBase="Shared\" />
    <Compile Include="$(SharedSourceRoot)InternalHeaderNames.cs" Link="Shared\" />
    <Compile Include="$(SharedSourceRoot)TransportTestHelpers\MsQuicSupportedAttribute.cs" LinkBase="Shared\" />
    <Compile Include="$(SharedSourceRoot)TransportTestHelpers\HttpSysHttp3SupportedAttribute.cs" LinkBase="shared\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="System.Diagnostics.EventLog" />
    <PackageReference Include="System.Net.Http.WinHttpHandler" />

    <ProjectReference Include="$(RepoRoot)src\Hosting\Abstractions\src\Microsoft.AspNetCore.Hosting.Abstractions.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Hosting\Hosting\src\Microsoft.AspNetCore.Hosting.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Http\Http.Abstractions\src\Microsoft.AspNetCore.Http.Abstractions.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Http\Http.Extensions\src\Microsoft.AspNetCore.Http.Extensions.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Http\Http.Features\src\Microsoft.AspNetCore.Http.Features.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Http\Http\src\Microsoft.AspNetCore.Http.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Servers\Kestrel\Core\src\Microsoft.AspNetCore.Server.Kestrel.Core.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Servers\Kestrel\Kestrel\src\Microsoft.AspNetCore.Server.Kestrel.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Servers\Kestrel\Transport.NamedPipes\src\Microsoft.AspNetCore.Server.Kestrel.Transport.NamedPipes.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Servers\Kestrel\Transport.Quic\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Servers\Kestrel\Transport.Sockets\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="$(SharedSourceRoot)ServerInfrastructure\SharedStrings.resx" Link="Shared\SharedStrings.resx">
      <ManifestResourceName>Microsoft.AspNetCore.Server.SharedStrings</ManifestResourceName>
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Include="$(SharedSourceRoot)runtime\SR.resx" Link="Shared\runtime\SR.resx">
      <ManifestResourceName>System.Net.Http.SR</ManifestResourceName>
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>
