<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>

    <DefineConstants Condition=" '$(GenerateSqlScripts)'=='true' ">$(DefineConstants);GENERATE_SQL_SCRIPTS</DefineConstants>
    <DefineConstants>$(DefineConstants);__RemoveThisBitTo__GENERATE_SQL_SCRIPTS</DefineConstants>

    <!-- Pomelo.EntityFrameworkCore.MySql is not strong named, so this test assembly cannot be strong-named signed either. -->
    <SignAssembly>false</SignAssembly>
    <IsTestAssetProject>true</IsTestAssetProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" VersionOverride="2.1.1" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" VersionOverride="2.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" VersionOverride="2.1.1" />
    <PackageReference Include="MySqlConnector" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />
  </ItemGroup>

  <!-- These references are used when running locally -->
  <ItemGroup Condition="'$(BenchmarksTargetFramework)' == ''">
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" />

    <ProjectReference Include="..\..\..\..\Middleware\StaticFiles\src\Microsoft.AspNetCore.StaticFiles.csproj" />
    <ProjectReference Include="..\..\..\..\Servers\IIS\IISIntegration\src\Microsoft.AspNetCore.Server.IISIntegration.csproj" />
    <ProjectReference Include="..\..\..\..\Servers\Kestrel\Kestrel\src\Microsoft.AspNetCore.Server.Kestrel.csproj" />
    <ProjectReference Include="..\..\..\Mvc.Abstractions\src\Microsoft.AspNetCore.Mvc.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Mvc.Core\src\Microsoft.AspNetCore.Mvc.Core.csproj" />
    <ProjectReference Include="..\..\..\Mvc.Razor\src\Microsoft.AspNetCore.Mvc.Razor.csproj" />
    <ProjectReference Include="..\..\..\Mvc\src\Microsoft.AspNetCore.Mvc.csproj" />
  </ItemGroup>
</Project>
