// <auto-generated />
namespace Microsoft.AspNet.Cors.Core
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Microsoft.AspNet.Cors.Core.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        /// The collection of headers '{0}' is not allowed.
        /// </summary>
        internal static string HeadersNotAllowed
        {
            get { return GetString("HeadersNotAllowed"); }
        }

        /// <summary>
        /// The collection of headers '{0}' is not allowed.
        /// </summary>
        internal static string FormatHeadersNotAllowed(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("HeadersNotAllowed"), p0);
        }

        /// <summary>
        /// The method '{0}' is not allowed.
        /// </summary>
        internal static string MethodNotAllowed
        {
            get { return GetString("MethodNotAllowed"); }
        }

        /// <summary>
        /// The method '{0}' is not allowed.
        /// </summary>
        internal static string FormatMethodNotAllowed(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("MethodNotAllowed"), p0);
        }

        /// <summary>
        /// The request does not contain the Origin header.
        /// </summary>
        internal static string NoOriginHeader
        {
            get { return GetString("NoOriginHeader"); }
        }

        /// <summary>
        /// The request does not contain the Origin header.
        /// </summary>
        internal static string FormatNoOriginHeader()
        {
            return GetString("NoOriginHeader");
        }

        /// <summary>
        /// The origin '{0}' is not allowed.
        /// </summary>
        internal static string OriginNotAllowed
        {
            get { return GetString("OriginNotAllowed"); }
        }

        /// <summary>
        /// The origin '{0}' is not allowed.
        /// </summary>
        internal static string FormatOriginNotAllowed(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("OriginNotAllowed"), p0);
        }

        /// <summary>
        /// PreflightMaxAge must be greater than or equal to 0.
        /// </summary>
        internal static string PreflightMaxAgeOutOfRange
        {
            get { return GetString("PreflightMaxAgeOutOfRange"); }
        }

        /// <summary>
        /// PreflightMaxAge must be greater than or equal to 0.
        /// </summary>
        internal static string FormatPreflightMaxAgeOutOfRange()
        {
            return GetString("PreflightMaxAgeOutOfRange");
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
