//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNet.Razor.Resources
{
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RazorResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RazorResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
#if NET45
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNet.Razor.Resources.RazorResources", typeof(RazorResources).Assembly);
#else
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNet.Razor.Resources.RazorResources", typeof(RazorResources).GetTypeInfo().Assembly);
#endif
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The active parser must the same as either the markup or code parser..
        /// </summary>
        internal static string ActiveParser_Must_Be_Code_Or_Markup_Parser
        {
            get
            {
                return ResourceManager.GetString("ActiveParser_Must_Be_Code_Or_Markup_Parser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Block cannot be built because a Type has not been specified in the BlockBuilder.
        /// </summary>
        internal static string Block_Type_Not_Specified
        {
            get
            {
                return ResourceManager.GetString("Block_Type_Not_Specified", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        internal static string BlockName_Code
        {
            get
            {
                return ResourceManager.GetString("BlockName_Code", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to explicit expression.
        /// </summary>
        internal static string BlockName_ExplicitExpression
        {
            get
            {
                return ResourceManager.GetString("BlockName_ExplicitExpression", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &quot;CancelBacktrack&quot; method can be called only while in a look-ahead process started with the &quot;BeginLookahead&quot; method..
        /// </summary>
        internal static string CancelBacktrack_Must_Be_Called_Within_Lookahead
        {
            get
            {
                return ResourceManager.GetString("CancelBacktrack_Must_Be_Called_Within_Lookahead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot call CreateCodeWriter, a CodeWriter was not provided to the Create method.
        /// </summary>
        internal static string CreateCodeWriter_NoCodeWriter
        {
            get
            {
                return ResourceManager.GetString("CreateCodeWriter_NoCodeWriter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;character literal&gt;&gt;.
        /// </summary>
        internal static string CSharpSymbol_CharacterLiteral
        {
            get
            {
                return ResourceManager.GetString("CSharpSymbol_CharacterLiteral", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;comment&gt;&gt;.
        /// </summary>
        internal static string CSharpSymbol_Comment
        {
            get
            {
                return ResourceManager.GetString("CSharpSymbol_Comment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;identifier&gt;&gt;.
        /// </summary>
        internal static string CSharpSymbol_Identifier
        {
            get
            {
                return ResourceManager.GetString("CSharpSymbol_Identifier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;integer literal&gt;&gt;.
        /// </summary>
        internal static string CSharpSymbol_IntegerLiteral
        {
            get
            {
                return ResourceManager.GetString("CSharpSymbol_IntegerLiteral", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;keyword&gt;&gt;.
        /// </summary>
        internal static string CSharpSymbol_Keyword
        {
            get
            {
                return ResourceManager.GetString("CSharpSymbol_Keyword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;newline sequence&gt;&gt;.
        /// </summary>
        internal static string CSharpSymbol_Newline
        {
            get
            {
                return ResourceManager.GetString("CSharpSymbol_Newline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;real literal&gt;&gt;.
        /// </summary>
        internal static string CSharpSymbol_RealLiteral
        {
            get
            {
                return ResourceManager.GetString("CSharpSymbol_RealLiteral", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;string literal&gt;&gt;.
        /// </summary>
        internal static string CSharpSymbol_StringLiteral
        {
            get
            {
                return ResourceManager.GetString("CSharpSymbol_StringLiteral", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;white space&gt;&gt;.
        /// </summary>
        internal static string CSharpSymbol_Whitespace
        {
            get
            {
                return ResourceManager.GetString("CSharpSymbol_Whitespace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;EndBlock&quot; was called without a matching call to &quot;StartBlock&quot;..
        /// </summary>
        internal static string EndBlock_Called_Without_Matching_StartBlock
        {
            get
            {
                return ResourceManager.GetString("EndBlock_Called_Without_Matching_StartBlock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; character.
        /// </summary>
        internal static string ErrorComponent_Character
        {
            get
            {
                return ResourceManager.GetString("ErrorComponent_Character", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to end of file.
        /// </summary>
        internal static string ErrorComponent_EndOfFile
        {
            get
            {
                return ResourceManager.GetString("ErrorComponent_EndOfFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to line break.
        /// </summary>
        internal static string ErrorComponent_Newline
        {
            get
            {
                return ResourceManager.GetString("ErrorComponent_Newline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to space or line break.
        /// </summary>
        internal static string ErrorComponent_Whitespace
        {
            get
            {
                return ResourceManager.GetString("ErrorComponent_Whitespace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;newline sequence&gt;&gt;.
        /// </summary>
        internal static string HtmlSymbol_NewLine
        {
            get
            {
                return ResourceManager.GetString("HtmlSymbol_NewLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;razor comment&gt;&gt;.
        /// </summary>
        internal static string HtmlSymbol_RazorComment
        {
            get
            {
                return ResourceManager.GetString("HtmlSymbol_RazorComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;text&gt;&gt;.
        /// </summary>
        internal static string HtmlSymbol_Text
        {
            get
            {
                return ResourceManager.GetString("HtmlSymbol_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;white space&gt;&gt;.
        /// </summary>
        internal static string HtmlSymbol_WhiteSpace
        {
            get
            {
                return ResourceManager.GetString("HtmlSymbol_WhiteSpace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot use built-in RazorComment handler, language characteristics does not define the CommentStart, CommentStar and CommentBody known symbol types or parser does not override TokenizerBackedParser.OutputSpanBeforeRazorComment.
        /// </summary>
        internal static string Language_Does_Not_Support_RazorComment
        {
            get
            {
                return ResourceManager.GetString("Language_Does_Not_Support_RazorComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &quot;@&quot; character must be followed by a &quot;:&quot;, &quot;(&quot;, or a C# identifier.  If you intended to switch to markup, use an HTML start tag, for example:
        ///
        ///@if(isLoggedIn) {
        ///    &lt;p&gt;Hello, @user!&lt;/p&gt;
        ///}.
        /// </summary>
        internal static string ParseError_AtInCode_Must_Be_Followed_By_Colon_Paren_Or_Identifier_Start
        {
            get
            {
                return ResourceManager.GetString("ParseError_AtInCode_Must_Be_Followed_By_Colon_Paren_Or_Identifier_Start", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End of file was reached before the end of the block comment.  All comments started with &quot;/*&quot; sequence must be terminated with a matching &quot;*/&quot; sequence..
        /// </summary>
        internal static string ParseError_BlockComment_Not_Terminated
        {
            get
            {
                return ResourceManager.GetString("ParseError_BlockComment_Not_Terminated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; block was not terminated.  All &quot;{0}&quot; statements must be terminated with a matching &quot;{1}&quot;..
        /// </summary>
        internal static string ParseError_BlockNotTerminated
        {
            get
            {
                return ResourceManager.GetString("ParseError_BlockNotTerminated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An opening &quot;{0}&quot; is missing the corresponding closing &quot;{1}&quot;..
        /// </summary>
        internal static string ParseError_Expected_CloseBracket_Before_EOF
        {
            get
            {
                return ResourceManager.GetString("ParseError_Expected_CloseBracket_Before_EOF", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The {0} block is missing a closing &quot;{1}&quot; character.  Make sure you have a matching &quot;{1}&quot; character for all the &quot;{2}&quot; characters within this block, and that none of the &quot;{1}&quot; characters are being interpreted as markup..
        /// </summary>
        internal static string ParseError_Expected_EndOfBlock_Before_EOF
        {
            get
            {
                return ResourceManager.GetString("ParseError_Expected_EndOfBlock_Before_EOF", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected &quot;{0}&quot;..
        /// </summary>
        internal static string ParseError_Expected_X
        {
            get
            {
                return ResourceManager.GetString("ParseError_Expected_X", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Helper blocks cannot be nested within each other..
        /// </summary>
        internal static string ParseError_Helpers_Cannot_Be_Nested
        {
            get
            {
                return ResourceManager.GetString("ParseError_Helpers_Cannot_Be_Nested", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;inherits&apos; keyword must be followed by a type name on the same line..
        /// </summary>
        internal static string ParseError_InheritsKeyword_Must_Be_Followed_By_TypeName
        {
            get
            {
                return ResourceManager.GetString("ParseError_InheritsKeyword_Must_Be_Followed_By_TypeName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inline markup blocks (@&lt;p&gt;Content&lt;/p&gt;) cannot be nested.  Only one level of inline markup is allowed..
        /// </summary>
        internal static string ParseError_InlineMarkup_Blocks_Cannot_Be_Nested
        {
            get
            {
                return ResourceManager.GetString("ParseError_InlineMarkup_Blocks_Cannot_Be_Nested", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;{1}&quot; is not a valid value for the &quot;{0}&quot; option. The &quot;Option {0}&quot; statement must be followed by either &quot;On&quot; or &quot;Off&quot;. .
        /// </summary>
        internal static string ParseError_InvalidOptionValue
        {
            get
            {
                return ResourceManager.GetString("ParseError_InvalidOptionValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Markup in a code block must start with a tag and all start tags must be matched with end tags.  Do not use unclosed tags like &quot;&lt;br&gt;&quot;.  Instead use self-closing tags like &quot;&lt;br/&gt;&quot;..
        /// </summary>
        internal static string ParseError_MarkupBlock_Must_Start_With_Tag
        {
            get
            {
                return ResourceManager.GetString("ParseError_MarkupBlock_Must_Start_With_Tag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected a &quot;{0}&quot; after the helper name..
        /// </summary>
        internal static string ParseError_MissingCharAfterHelperName
        {
            get
            {
                return ResourceManager.GetString("ParseError_MissingCharAfterHelperName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected a &quot;{0}&quot; after the helper parameters..
        /// </summary>
        internal static string ParseError_MissingCharAfterHelperParameters
        {
            get
            {
                return ResourceManager.GetString("ParseError_MissingCharAfterHelperParameters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; element was not closed.  All elements must be either self-closing or have a matching end tag..
        /// </summary>
        internal static string ParseError_MissingEndTag
        {
            get
            {
                return ResourceManager.GetString("ParseError_MissingEndTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sections cannot be empty.  The &quot;@section&quot; keyword must be followed by a block of markup surrounded by &quot;{}&quot;.  For example:
        ///
        ///@section Sidebar {
        ///   &lt;!-- Markup and text goes here --&gt;
        ///}.
        /// </summary>
        internal static string ParseError_MissingOpenBraceAfterSection
        {
            get
            {
                return ResourceManager.GetString("ParseError_MissingOpenBraceAfterSection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Namespace imports and type aliases cannot be placed within code blocks.  They must immediately follow an &quot;@&quot; character in markup.  It is recommended that you put them at the top of the page, as in the following example:
        ///
        ///@using System.Drawing;
        ///@{
        ///    // OK here to use types from System.Drawing in the page.
        ///}.
        /// </summary>
        internal static string ParseError_NamespaceImportAndTypeAlias_Cannot_Exist_Within_CodeBlock
        {
            get
            {
                return ResourceManager.GetString("ParseError_NamespaceImportAndTypeAlias_Cannot_Exist_Within_CodeBlock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &quot;Imports&quot; keyword must be followed by a namespace or a type alias on the same line..
        /// </summary>
        internal static string ParseError_NamespaceOrTypeAliasExpected
        {
            get
            {
                return ResourceManager.GetString("ParseError_NamespaceOrTypeAliasExpected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Outer tag is missing a name. The first character of a markup block must be an HTML tag with a valid name..
        /// </summary>
        internal static string ParseError_OuterTagMissingName
        {
            get
            {
                return ResourceManager.GetString("ParseError_OuterTagMissingName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End of file was reached before the end of the block comment.  All comments that start with the &quot;@*&quot; sequence must be terminated with a matching &quot;*@&quot; sequence..
        /// </summary>
        internal static string ParseError_RazorComment_Not_Terminated
        {
            get
            {
                return ResourceManager.GetString("ParseError_RazorComment_Not_Terminated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is a reserved word and cannot be used in implicit expressions.  An explicit expression (&quot;@()&quot;) must be used..
        /// </summary>
        internal static string ParseError_ReservedWord
        {
            get
            {
                return ResourceManager.GetString("ParseError_ReservedWord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Section blocks (&quot;{0}&quot;) cannot be nested.  Only one level of section blocks are allowed..
        /// </summary>
        internal static string ParseError_Sections_Cannot_Be_Nested
        {
            get
            {
                return ResourceManager.GetString("ParseError_Sections_Cannot_Be_Nested", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected a &quot;{0}&quot; but found a &quot;{1}&quot;.  Block statements must be enclosed in &quot;{{&quot; and &quot;}}&quot;.  You cannot use single-statement control-flow statements in CSHTML pages. For example, the following is not allowed:
        ///
        ///@if(isLoggedIn)
        ///    &lt;p&gt;Hello, @user&lt;/p&gt;
        ///
        ///Instead, wrap the contents of the block in &quot;{{}}&quot;:
        ///
        ///@if(isLoggedIn) {{
        ///    &lt;p&gt;Hello, @user&lt;/p&gt;
        ///}}.
        /// </summary>
        internal static string ParseError_SingleLine_ControlFlowStatements_Not_Allowed
        {
            get
            {
                return ResourceManager.GetString("ParseError_SingleLine_ControlFlowStatements_Not_Allowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;text&gt;&quot; and &quot;&lt;/text&gt;&quot; tags cannot contain attributes..
        /// </summary>
        internal static string ParseError_TextTagCannotContainAttributes
        {
            get
            {
                return ResourceManager.GetString("ParseError_TextTagCannotContainAttributes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected &quot;{0}&quot;.
        /// </summary>
        internal static string ParseError_Unexpected
        {
            get
            {
                return ResourceManager.GetString("ParseError_Unexpected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected {0} after helper keyword.  All helpers must have a name which starts with an &quot;_&quot; or alphabetic character. The remaining characters must be either &quot;_&quot; or alphanumeric..
        /// </summary>
        internal static string ParseError_Unexpected_Character_At_Helper_Name_Start
        {
            get
            {
                return ResourceManager.GetString("ParseError_Unexpected_Character_At_Helper_Name_Start", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected {0} after section keyword.  Section names must start with an &quot;_&quot; or alphabetic character, and the remaining characters must be either &quot;_&quot; or alphanumeric..
        /// </summary>
        internal static string ParseError_Unexpected_Character_At_Section_Name_Start
        {
            get
            {
                return ResourceManager.GetString("ParseError_Unexpected_Character_At_Section_Name_Start", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not valid at the start of a code block.  Only identifiers, keywords, comments, &quot;(&quot; and &quot;{{&quot; are valid..
        /// </summary>
        internal static string ParseError_Unexpected_Character_At_Start_Of_CodeBlock_CS
        {
            get
            {
                return ResourceManager.GetString("ParseError_Unexpected_Character_At_Start_Of_CodeBlock_CS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End-of-file was found after the &quot;@&quot; character.  &quot;@&quot; must be followed by a valid code block.  If you want to output an &quot;@&quot;, escape it using the sequence: &quot;@@&quot;.
        /// </summary>
        internal static string ParseError_Unexpected_EndOfFile_At_Start_Of_CodeBlock
        {
            get
            {
                return ResourceManager.GetString("ParseError_Unexpected_EndOfFile_At_Start_Of_CodeBlock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected &quot;{0}&quot; keyword after &quot;@&quot; character.  Once inside code, you do not need to prefix constructs like &quot;{0}&quot; with &quot;@&quot;..
        /// </summary>
        internal static string ParseError_Unexpected_Keyword_After_At
        {
            get
            {
                return ResourceManager.GetString("ParseError_Unexpected_Keyword_After_At", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected &quot;{&quot; after &quot;@&quot; character. Once inside the body of a code block (@if {}, @{}, etc.) you do not need to use &quot;@{&quot; to switch to code..
        /// </summary>
        internal static string ParseError_Unexpected_Nested_CodeBlock
        {
            get
            {
                return ResourceManager.GetString("ParseError_Unexpected_Nested_CodeBlock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A space or line break was encountered after the &quot;@&quot; character.  Only valid identifiers, keywords, comments, &quot;(&quot; and &quot;{&quot; are valid at the start of a code block and they must occur immediately following &quot;@&quot; with no space in between..
        /// </summary>
        internal static string ParseError_Unexpected_WhiteSpace_At_Start_Of_CodeBlock_CS
        {
            get
            {
                return ResourceManager.GetString("ParseError_Unexpected_WhiteSpace_At_Start_Of_CodeBlock_CS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encountered end tag &quot;{0}&quot; with no matching start tag.  Are your start/end tags properly balanced?.
        /// </summary>
        internal static string ParseError_UnexpectedEndTag
        {
            get
            {
                return ResourceManager.GetString("ParseError_UnexpectedEndTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End of file or an unexpected character was reached before the &quot;{0}&quot; tag could be parsed.  Elements inside markup blocks must be complete. They must either be self-closing (&quot;&lt;br /&gt;&quot;) or have matching end tags (&quot;&lt;p&gt;Hello&lt;/p&gt;&quot;).  If you intended to display a &quot;&lt;&quot; character, use the &quot;&amp;lt;&quot; HTML entity..
        /// </summary>
        internal static string ParseError_UnfinishedTag
        {
            get
            {
                return ResourceManager.GetString("ParseError_UnfinishedTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown option: &quot;{0}&quot;..
        /// </summary>
        internal static string ParseError_UnknownOption
        {
            get
            {
                return ResourceManager.GetString("ParseError_UnknownOption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unterminated string literal.  Strings that start with a quotation mark (&quot;) must be terminated before the end of the line.  However, strings that start with @ and a quotation mark (@&quot;) can span multiple lines..
        /// </summary>
        internal static string ParseError_Unterminated_String_Literal
        {
            get
            {
                return ResourceManager.GetString("ParseError_Unterminated_String_Literal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Helper parameter list is missing a closing &quot;)&quot;..
        /// </summary>
        internal static string ParseError_UnterminatedHelperParameterList
        {
            get
            {
                return ResourceManager.GetString("ParseError_UnterminatedHelperParameterList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parser was started with a null Context property.  The Context property must be set BEFORE calling any methods on the parser..
        /// </summary>
        internal static string Parser_Context_Not_Set
        {
            get
            {
                return ResourceManager.GetString("Parser_Context_Not_Set", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot complete the tree, StartBlock must be called at least once..
        /// </summary>
        internal static string ParserContext_CannotCompleteTree_NoRootBlock
        {
            get
            {
                return ResourceManager.GetString("ParserContext_CannotCompleteTree_NoRootBlock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot complete the tree, there are still open blocks..
        /// </summary>
        internal static string ParserContext_CannotCompleteTree_OutstandingBlocks
        {
            get
            {
                return ResourceManager.GetString("ParserContext_CannotCompleteTree_OutstandingBlocks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot finish span, there is no current block. Call StartBlock at least once before finishing a span.
        /// </summary>
        internal static string ParserContext_NoCurrentBlock
        {
            get
            {
                return ResourceManager.GetString("ParserContext_NoCurrentBlock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot complete action, the parser has finished. Only CompleteParse can be called to extract the final parser results after the parser has finished.
        /// </summary>
        internal static string ParserContext_ParseComplete
        {
            get
            {
                return ResourceManager.GetString("ParserContext_ParseComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing value for session state directive..
        /// </summary>
        internal static string ParserEror_SessionDirectiveMissingValue
        {
            get
            {
                return ResourceManager.GetString("ParserEror_SessionDirectiveMissingValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The parser provided to the ParserContext was not a Markup Parser..
        /// </summary>
        internal static string ParserIsNotAMarkupParser
        {
            get
            {
                return ResourceManager.GetString("ParserIsNotAMarkupParser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to @section Header { ... }.
        /// </summary>
        internal static string SectionExample_CS
        {
            get
            {
                return ResourceManager.GetString("SectionExample_CS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The {0} property of the {1} structure cannot be null..
        /// </summary>
        internal static string Structure_Member_CannotBeNull
        {
            get
            {
                return ResourceManager.GetString("Structure_Member_CannotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;unknown&gt;&gt;.
        /// </summary>
        internal static string Symbol_Unknown
        {
            get
            {
                return ResourceManager.GetString("Symbol_Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot resume this symbol. Only the symbol immediately preceding the current one can be resumed..
        /// </summary>
        internal static string Tokenizer_CannotResumeSymbolUnlessIsPrevious
        {
            get
            {
                return ResourceManager.GetString("Tokenizer_CannotResumeSymbolUnlessIsPrevious", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In order to put a symbol back, it must have been the symbol which ended at the current position. The specified symbol ends at {0}, but the current position is {1}.
        /// </summary>
        internal static string TokenizerView_CannotPutBack
        {
            get
            {
                return ResourceManager.GetString("TokenizerView_CannotPutBack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [BG][{0}] Shutdown.
        /// </summary>
        internal static string Trace_BackgroundThreadShutdown
        {
            get
            {
                return ResourceManager.GetString("Trace_BackgroundThreadShutdown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [BG][{0}] Startup.
        /// </summary>
        internal static string Trace_BackgroundThreadStart
        {
            get
            {
                return ResourceManager.GetString("Trace_BackgroundThreadStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [BG][{0}] {1} changes arrived.
        /// </summary>
        internal static string Trace_ChangesArrived
        {
            get
            {
                return ResourceManager.GetString("Trace_ChangesArrived", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [BG][{0}] Discarded {1} changes.
        /// </summary>
        internal static string Trace_ChangesDiscarded
        {
            get
            {
                return ResourceManager.GetString("Trace_ChangesDiscarded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [BG][{0}] Collecting {1} discarded changes.
        /// </summary>
        internal static string Trace_CollectedDiscardedChanges
        {
            get
            {
                return ResourceManager.GetString("Trace_CollectedDiscardedChanges", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Trace_Disabled
        {
            get
            {
                return ResourceManager.GetString("Trace_Disabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [P][{0}] {3} Change in {2} milliseconds: {1}.
        /// </summary>
        internal static string Trace_EditorProcessedChange
        {
            get
            {
                return ResourceManager.GetString("Trace_EditorProcessedChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [P][{0}] Received Change: {1}.
        /// </summary>
        internal static string Trace_EditorReceivedChange
        {
            get
            {
                return ResourceManager.GetString("Trace_EditorReceivedChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Trace_Enabled
        {
            get
            {
                return ResourceManager.GetString("Trace_Enabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [Razor] {0}.
        /// </summary>
        internal static string Trace_Format
        {
            get
            {
                return ResourceManager.GetString("Trace_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [BG][{0}] no changes arrived?.
        /// </summary>
        internal static string Trace_NoChangesArrived
        {
            get
            {
                return ResourceManager.GetString("Trace_NoChangesArrived", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [BG][{0}] Parse Complete in {1} milliseconds.
        /// </summary>
        internal static string Trace_ParseComplete
        {
            get
            {
                return ResourceManager.GetString("Trace_ParseComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [M][{0}] Queuing Parse for: {1}.
        /// </summary>
        internal static string Trace_QueuingParse
        {
            get
            {
                return ResourceManager.GetString("Trace_QueuingParse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [Razor] Editor Tracing {0}.
        /// </summary>
        internal static string Trace_Startup
        {
            get
            {
                return ResourceManager.GetString("Trace_Startup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [BG][{0}] Trees Compared in {1} milliseconds. Different = {2}.
        /// </summary>
        internal static string Trace_TreesCompared
        {
            get
            {
                return ResourceManager.GetString("Trace_TreesCompared", resourceCulture);
            }
        }
    }
}
