@Company.ApiApplication1_HostAddress = http://localhost:5000

GET {{Company.ApiApplication1_HostAddress}}/todos/
Accept: application/json

###

GET {{Company.ApiApplication1_HostAddress}}/todos/1
Accept: application/json

###
