# This runs code signing for .nupkg files built on MacOS or Linux
parameters:
  inputName: ''

jobs:
- template: default-build.yml
  parameters:
    dependsOn:
    - ${{ parameters.inputName }}_build
    condition: in(variables['_SignType'], 'test', 'real')
    jobName: CodeSign_Xplat_${{ parameters.inputName }}
    jobDisplayName: "Code-sign ${{ parameters.inputName }} packages"
    agentOs: Windows
    beforeBuild:
    - task: DownloadBuildArtifacts@0
      displayName: Download ${{ parameters.inputName }} artifacts
      inputs:
        artifactName: ${{ parameters.inputName }}_Packages
        downloadPath: $(Build.StagingDirectory)/deps/
        itemPattern: '**/*.nupkg'
    buildScript: eng\tools\XplatPackageSigner\sign-packages.cmd $(Build.StagingDirectory)\deps\${{ parameters.inputName }}Packages\
    artifacts:
    - name: ${{ parameters.inputName }}_Packages_Signed
      path: $(Build.StagingDirectory)\deps\${{ parameters.inputName }}Packages\
