# This runs code signing for .nupkg files built on MacOS or Linux
parameters:
  inputName: ''

jobs:
- template: default-build.yml
  parameters:
    codeSign: true
    dependsOn:
    - ${{ parameters.inputName }}_build
    condition: and(in(variables['_SignType'], 'test', 'real'), in(dependencies.${{ parameters.inputName }}_build.result, 'Succeeded', 'SucceededWithIssues'))
    jobName: CodeSign_Xplat_${{ parameters.inputName }}
    jobDisplayName: "Code-sign ${{ parameters.inputName }} packages"
    agentOs: Windows
    installNodeJs: false
    installJdk: false
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: Download ${{ parameters.inputName }} artifacts
      inputs:
        artifactName: ${{ parameters.inputName }}_Packages
        downloadPath: $(Build.StagingDirectory)/downloaded_packages/
        itemPattern: '**/*.nupkg'
    - task: CopyFiles@2
      displayName: Copy packages to ArtifactsShippingPackagesDir
      inputs:
        sourceFolder: $(Build.StagingDirectory)/downloaded_packages/
        contents: '**/*.nupkg'
        targetFolder: $(Build.SourcesDirectory)/artifacts/packages/$(BuildConfiguration)/shipping/
        flattenFolders: true
    - ${{ if ne(variables['System.TeamProject'], 'public') }}:
      - task: PowerShell@2
        displayName: Setup Private Feeds Credentials
        inputs:
          filePath: $(Build.SourcesDirectory)/eng/common/SetupNugetSources.ps1
          arguments: -ConfigFile $(Build.SourcesDirectory)/NuGet.config -Password $Env:Token
        env:
          Token: $(dn-bot-dnceng-artifact-feeds-rw)
    - powershell: .\eng\common\build.ps1
        -ci
        -restore
        -sign
        -publish
        -configuration $(BuildConfiguration)
        -projects $(Build.SourcesDirectory)/eng/empty.proj
        /p:AssetManifestFileName=aspnetcore-${{ parameters.inputName }}-signed.xml
        /p:DotNetSignType=$(_SignType)
        $(_BuildArgs)
        $(_PublishArgs)
        $(_InternalRuntimeDownloadCodeSignArgs)
      displayName: Sign and publish packages
    artifacts:
    - name: CodeSign_Xplat_${{ parameters.inputName }}_Logs
      path: artifacts/log/
      publishOnError: true
      includeForks: true
    - name: ${{ parameters.inputName }}_Packages_Signed
      path: artifacts/packages/
