// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
    using static Test2.SomeComponent;
    using Foo = Test3;
    public class TestComponent : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder builder)
        {
            builder.OpenComponent<Test.MyComponent>(0);
            builder.CloseComponent();
            builder.AddMarkupContent(1, "\r\n<SomeComponent></SomeComponent>");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
