<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <SignAssembly>false</SignAssembly>
    <AssemblyName>Diagnostics.FunctionalTests</AssemblyName>
    <TestDependsOnMssql>true</TestDependsOnMssql> 
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)src\Middleware\Diagnostics\test\testassets\DatabaseErrorPageSample\DatabaseErrorPageSample.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Middleware\Diagnostics\test\testassets\DeveloperExceptionPageSample\DeveloperExceptionPageSample.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Middleware\Diagnostics\test\testassets\ExceptionHandlerSample\ExceptionHandlerSample.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Middleware\Diagnostics\test\testassets\StatusCodePagesSample\StatusCodePagesSample.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Middleware\Diagnostics\test\testassets\WelcomePageSample\WelcomePageSample.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Middleware\MiddlewareAnalysis\samples\MiddlewareAnalysisSample\MiddlewareAnalysisSample.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)src\Hosting\TestHost\src\Microsoft.AspNetCore.TestHost.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Http\Routing.Abstractions\src\Microsoft.AspNetCore.Routing.Abstractions.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Http\Routing\src\Microsoft.AspNetCore.Routing.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Servers\Kestrel\Kestrel\src\Microsoft.AspNetCore.Server.Kestrel.csproj" />
  </ItemGroup>

</Project>
