<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <Nullable>enable</Nullable>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.AspNetCore.Components.Platform" />
    <Reference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <Reference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

</Project>
