//
// this file is automatically generated
// by beaver.exe 1.11.2003.0
//

//
// if you want to use a private version file and customize this, see
// file://samsndrop02/CoreXT-Latest/docs/corext/corext/version.htm
//

#ifndef _BLDVER_H_
#define _BLDVER_H_

#define BUILD_NUMBER            "1965.0"
#define BUILD_NUM               1965,0
#define PRODUCT_NUMBER          "7.1"
#define PRODUCT_NUM             7,1
#define INET_VERSION            "7.1.1965.0"
#define INET_VERSION_L          L"7.1.1965.0"
#define INET_VER                7,1,1965,0

#define PRODUCT_MAJOR           7
#define PRODUCT_MAJOR_STRING    "7"
#define PRODUCT_MAJOR_NUMBER    7

#define PRODUCT_MINOR           1
#define PRODUCT_MINOR_STRING    "1"
#define PRODUCT_MINOR_NUMBER    1

#define BUILD_MAJOR             1965
#define BUILD_MAJOR_STRING      "1965"
#define BUILD_MAJOR_NUMBER      1965

#define BUILD_MINOR             0
#define BUILD_MINOR_STRING      "0"
#define BUILD_MINOR_NUMBER      0

#define BUILD_PRIVATE           "Built by panwang on IIS-OOB.\0"

// beaver.exe can't handle a pragma to disable redefinition
#undef VER_PRODUCTVERSION
#undef VER_PRODUCTVERSION_STR
#undef VER_PRODUCTMAJORVERSION
#undef VER_PRODUCTMINORVERSION
#undef VER_PRODUCTBUILD
#undef VER_PRODUCTBUILD_QFE
#undef VER_PRODUCTNAME_STR
#undef VER_COMPANYNAME_STR

#define VER_PRODUCTVERSION      7,1,1965,0
#define VER_PRODUCTVERSION_STR  7.1.1965.0
#define VER_PRODUCTMAJORVERSION 7
#define VER_PRODUCTMINORVERSION 1
#define VER_PRODUCTBUILD        1965
#define VER_PRODUCTBUILD_QFE    0
#define VER_PRODUCTNAME_STR     "Microsoft Web Platform Extensions"
#define VER_COMPANYNAME_STR     "Microsoft Corporation"



#endif
