<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateLoggingTestingAssemblyAttributes>false</GenerateLoggingTestingAssemblyAttributes>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <TestRunnerName>Microsoft.Testing.Platform</TestRunnerName>
    <TestRunnerAdditionalArguments>--filter "TestCategory!=Quarantined"</TestRunnerAdditionalArguments>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <DisablePackageReferenceRestrictions>true</DisablePackageReferenceRestrictions>
    <NoWarn>$(NoWarn);CA1310;ASPNETCORE9004;NETSDK1023;MSTEST0001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Reference Remove="Microsoft.AspNetCore.InternalTesting" />
    <Reference Remove="Moq" />
    <Compile Remove="$(SharedSourceRoot)test\SuccessfulTests.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MSTest.TestFramework" />
    <Reference Include="Microsoft.Testing.Extensions.TrxReport" />
    <Reference Include="Microsoft.CodeAnalysis.CSharp" />
    <Reference Include="Microsoft.AspNetCore.Authorization" />
    <Reference Include="Microsoft.AspNetCore.Authorization.Policy" />
    <Reference Include="Microsoft.AspNetCore.Components" />
    <Reference Include="Microsoft.AspNetCore.Components.Authorization" />
    <Reference Include="Microsoft.AspNetCore.Components.Endpoints" />
    <Reference Include="Microsoft.AspNetCore.Components.Forms" />
    <Reference Include="Microsoft.AspNetCore.Components.Media" />
    <Reference Include="Microsoft.AspNetCore.Components.QuickGrid" />
    <Reference Include="Microsoft.AspNetCore.Components.Web" />
    <Reference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />
    <Reference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <Reference Include="Microsoft.AspNetCore.Http" />
    <Reference Include="Microsoft.AspNetCore.Http.Features" />
    <Reference Include="Microsoft.JSInterop" />
    <Reference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestAdapter" Version="$(MSTestVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\gen\Microsoft.AspNetCore.Components.Endpoints.Generators.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>ArtifactsShippingPackagesDir</_Parameter1>
      <_Parameter2>$(ArtifactsShippingPackagesDir)</_Parameter2>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>DotNetHostPath</_Parameter1>
      <_Parameter2>$(DOTNET_HOST_PATH)</_Parameter2>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>DefaultNetCoreTargetFramework</_Parameter1>
      <_Parameter2>$(DefaultNetCoreTargetFramework)</_Parameter2>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>AspNetCorePackageVersion</_Parameter1>
      <_Parameter2>$(PackageVersion)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

  <Target Name="PackGeneratorForTests" BeforeTargets="RunTests">
    <MSBuild Projects="..\..\gen\Microsoft.AspNetCore.Components.Endpoints.Generators.csproj"
             Targets="Pack"
             RemoveProperties="RuntimeIdentifier;SelfContained;PublishAot"
             Properties="Configuration=$(Configuration)" />
  </Target>

  <Target Name="RemoveXunitGlobalUsing" BeforeTargets="GenerateGlobalUsings">
    <ItemGroup>
      <Using Remove="Xunit" />
    </ItemGroup>
  </Target>

</Project>
