<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(DefaultNetCoreTargetFramework);net472</TargetFrameworks>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)src\Shared\test\testassets\MockHostTypes\MockHostTypes.csproj" />
  </ItemGroup>

</Project>
