'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:N.N.NNNNN.N
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Foo = System.Text.Encoding

Imports System
Imports System.IO


Namespace TestOutput
Public Class [Imports]
Private Shared __o As Object
Public Sub New()
MyBase.New
End Sub
Public Overrides Sub Execute()

#ExternalSource("Imports.vbhtml",4)
                       __o = GetType(Path).FullName


#End ExternalSource

#ExternalSource("Imports.vbhtml",5)
                             __o = GetType(Foo).FullName


#End ExternalSource
End Sub
End Class
End Namespace
