name: "Request Dep Updates"
description: "Automated issue to update Browser-Testing dependencies"
title: "Request Browser-Testing Dependencies Update"
labels:
  - dependencies
  - automation
  - selenium
  - playwright
body:
  - type: markdown
    attributes:
      value: |
        This issue is configured to request an update of the Browser-Testing dependencies used in the project.
        Copilot will automatically create a pull request to update the dependencies.
        You can include more context to the issue description if you want to.
  - type: textarea
    id: update-notes
    attributes:
      label: Requested Browser-Testing Dependencies Update Notes
      description: Adjust the description if you think it requires more context
      # NOTE: update the `_body.md` as well if you are changing the text.
      # It is used for automatic workflow of issue creation.
      value: |
        ## Description

        Selenium is used in the aspnetcore repo for automated E2E integration testing.
        Playwright is used in the aspnetcore repo for some benchmarking apps. We need to ensure the docker file and the package version match.

        ## Instructions

        To update the Selenium and Playwright versions, these files need to be updated:

        ### Packages
          - [ ] [Selenium in `Versions.props`](eng/Versions.props) from NuGet:
            - [ ] [Selenium.WebDriver](https://www.nuget.org/packages/Selenium.WebDriver/) (Config variable `SeleniumWebDriverVersion`)
            - [ ] [Selenium.Support](https://www.nuget.org/packages/Selenium.Support/) (Config variable `SeleniumSupportVersion`)
          - [ ] Ensure Playwright versions match
            - [ ]  [Blazor Wasm benchmarks in `src/Components/benchmarkapps/Wasm.Performance/dockerfile`](src/Components/benchmarkapps/Wasm.Performance/dockerfile) (image starts with `mcr.microsoft.com`)
            - [ ]  [Playwright package version](eng/Versions.props) (Config variable `PlaywrightVersion`)

        ## Actions

        Please, open the PR against `main` branch and include changes to the files listed above.

