#pragma classflags("forceupdate")
#pragma namespace ("\\\\.\\Root\\WMI")
#pragma autorecover

/*
 * AspNetCore module trace events layout
 * Uncomment the following class to run mof2trace to generate header file
 * comment it back before checking it in
[Dynamic,
  Description("IIS: WWW Server"),
  Guid("{3a2a4e84-4c21-4981-ae10-3fda0d9b0f83}"),
  locale("MS\\0x409")]
class IIS_Trace:EventTrace
{
    [Description ("Enable Flags") : amended,
        ValueDescriptions{
            "AspNetCore module events" } : amended,
        DefineValues{
            "ETW_IIS_ANCM" },
        Values{
            "ANCM" },
        ValueMap{
            "0x10000" }
    ]
    uint32 Flags;

    [Description ("Levels") : amended,
        ValueDescriptions{
            "Abnormal exit or termination",
            "Severe errors",
            "Warnings",
            "Information",
            "Detailed information" } : amended,
         DefineValues{
            "TRACE_LEVEL_FATAL",
            "TRACE_LEVEL_ERROR",
            "TRACE_LEVEL_WARNING",
            "TRACE_LEVEL_INFORMATION",
            "TRACE_LEVEL_VERBOSE" },
        Values{
            "Fatal",
            "Error",
            "Warning",
            "Information",
            "Verbose" },
        ValueMap{
            "0x1",
            "0x2",
            "0x3",
            "0x4",
            "0x5" },
        ValueType("index")
    ]
    uint32 Level;
};
*/

[Dynamic,
 Description("ANCM runtime events") : amended,
 Guid("{82ADEAD7-12B2-4781-BDCA-5A4B6C757191}"),
 EventVersion(1),
 DisplayName("ANCM"),
 EventANCMRuntime,
 locale("MS\\0x409")
]
class ANCM_Events:IIS_Trace
{
};

[Dynamic,
 Description("Start application success") : amended,
 EventType(1),
 EventLevel(4),
 EventTypeName("ANCM_START_APPLICATION_SUCCESS") : amended
]
class ANCMAppStart:ANCM_Events
{
    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
    [WmiDataId(2),
     Description("Application Description") : amended,
     StringTermination("NullTerminated"),
     format("w"),
     read]
     string AppDescription;
};

[Dynamic,
 Description("Start application failed") : amended,
 EventType(2),
 EventLevel(2),
 EventTypeName("ANCM_START_APPLICATION_FAIL") : amended
]
class ANCMAppStartFail:ANCM_Events
{
    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
    [WmiDataId(2),
     Description("Application Start Failure Description") : amended,
     StringTermination("NullTerminated"),
     format("w"),
     read]
     string FailureDescription;
};

[Dynamic,
 Description("Start forwarding request") : amended,
 EventType(3),
 EventLevel(4),
 EventTypeName("ANCM_REQUEST_FORWARD_START") : amended
]
class ANCMForwardStart:ANCM_Events
{
    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic,
 Description("Finish forwarding request") : amended,
 EventType(4),
 EventLevel(4),
 EventTypeName("ANCM_REQUEST_FORWARD_END") : amended
]
class ANCMForwardEnd:ANCM_Events
{
    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic,
 Description("Forwarding request failure") : amended,
 EventType(5),
 EventLevel(2),
 EventTypeName("ANCM_REQUEST_FORWARD_FAIL") : amended
]
class ANCMForwardFail:ANCM_Events
{
    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
    [WmiDataId(2),
     Description("Error code") : amended,
     format("x"),
     read]
     uint32  ErrorCode;
};

[Dynamic,
 Description("Receiving callback from WinHttp") : amended,
 EventType(6),
 EventLevel(4),
 EventTypeName("ANCM_WINHTTP_CALLBACK") : amended
]
class ANCMWinHttpCallBack:ANCM_Events
{
    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
    [WmiDataId(2),
     Description("InternetStatus") : amended,
     format("x"),
     read]
     uint32  InternetStatus;
};

[Dynamic,
 Description("Starting inprocess execute request") : amended,
 EventType(7),
 EventLevel(4),
 EventTypeName("ANCM_INPROC_EXECUTE_REQUEST_START") : amended
]
class ANCMExecuteStart:ANCM_Events
{
    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic,
 Description("Ending inprocess execute request") : amended,
 EventType(8),
 EventLevel(5),
 EventTypeName("ANCM_INPROC_EXECUTE_REQUEST_COMPLETION") : amended
]
class ANCMExecuteEnd:ANCM_Events
{
    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
    [WmiDataId(2),
     Description("Notification status") : amended,
     format("d"),
     read]
     uint32  requestStatus;
};

[Dynamic,
 Description("Starting inprocess async completion") : amended,
 EventType(9),
 EventLevel(5),
 EventTypeName("ANCM_INPROC_ASYNC_COMPLETION_START") : amended
]
class ANCMAsyncStart:ANCM_Events
{
    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic,
 Description("Ending inprocess async completion") : amended,
 EventType(10),
 EventLevel(5),
 EventTypeName("ANCM_INPROC_ASYNC_COMPLETION_COMPLETION") : amended
]
class ANCMAsyncEnd:ANCM_Events
{
    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
    [WmiDataId(2),
     Description("Notification status") : amended,
     format("d"),
     read]
     uint32  requestStatus;
};

[Dynamic,
 Description("Inprocess app shutdown") : amended,
 EventType(11),
 EventLevel(4),
 EventTypeName("ANCM_INPROC_REQUEST_SHUTDOWN") : amended
]
class ANCMRequestShutdown:ANCM_Events
{
    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic,
 Description("Inprocess request disconnect") : amended,
 EventType(12),
 EventLevel(4),
 EventTypeName("ANCM_INPROC_REQUEST_DISCONNECT") : amended
]
class ANCMRequestDisconnect:ANCM_Events
{
    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic,
 Description("Indicate managed request complete") : amended,
 EventType(13),
 EventLevel(4),
 EventTypeName("ANCM_INPROC_MANAGED_REQUEST_COMPLETION") : amended
]
class ANCMManagedRequestCompletion:ANCM_Events
{
    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic,
 Description("Failed HRESULT") : amended,
 EventType(14),
 EventLevel(3),
 EventTypeName("ANCM_HRESULT_FAILED") : amended
]
class ANCMHRESULTFailed:ANCM_Events
{
    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
     [WmiDataId(2),
     Description("Failed source file location") : amended,
     StringTermination("NullTerminated"),
     read]
     string File;
     [WmiDataId(3),
     Description("Failed line number") : amended,
     format("d"),
     read]
     uint32 Line;
     [WmiDataId(4),
     Description("HResult") : amended,
     format("x"),
     read]
     uint32 HResult;
};

[Dynamic,
 Description("Caught exception") : amended,
 EventType(15),
 EventLevel(3),
 EventTypeName("ANCM_EXCEPTION_CAUGHT") : amended
]
class ANCMExceptionCaughFailed:ANCM_Events
{
    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
     [WmiDataId(2),
     Description("Exception catch file location") : amended,
     StringTermination("NullTerminated"),
     read]
     string File;
     [WmiDataId(3),
     Description("Exception catch line number") : amended,
     format("d"),
     read]
     uint32 Line;
     [WmiDataId(2),
     Description("Exception description") : amended,
     StringTermination("NullTerminated"),
     read]
     string Description;
};

