parameters:
  ChannelId: 0

jobs:
- job:
  displayName: Promote Build
  dependsOn: setupMaestroVars
  condition: contains(dependencies.setupMaestroVars.outputs['setReleaseVars.InitialChannels'], format('[{0}]', ${{ parameters.ChannelId }}))
  variables:
    - name: BARBuildId
      value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.BARBuildId'] ]
    - name: ChannelId
      value: ${{ parameters.ChannelId }}
  pool:
    name: NetCore1ESPool-Svc-Internal
    demands: ImageOverride -equals windows.vs2019.amd64
  steps:
    - task: PowerShell@2
      displayName: Add Build to Channel
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/common/post-build/promote-build.ps1
        arguments: -BuildId $(BARBuildId)
          -ChannelId $(ChannelId)
          -MaestroApiAccessToken $(MaestroApiAccessToken)
          -MaestroApiEndPoint $(MaestroApiEndPoint)
          -MaestroApiVersion $(MaestroApiVersion)
