<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(DefaultNetCoreTargetFramework);$(DefaultNetFxTargetFramework)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="File.txt;sub\**\*;Resources\**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="sub\sub-dir\File3.txt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)src\FileProviders\Embedded\src\Microsoft.Extensions.FileProviders.Embedded.csproj" />
  </ItemGroup>

  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net12.0'))">
    <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Primitives" />
  </ItemGroup>

</Project>
