<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>
      Components for performing health checks using EntityFrameworkCore.
    </Description>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageTags>diagnostics;healthchecks;entityframeworkcore</PackageTags>
    <BaseNamespace>Microsoft.Extensions.Diagnostics.HealthChecks</BaseNamespace>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />

    <ProjectReference Include="$(RepoRoot)src\HealthChecks\Abstractions\src\Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions.csproj" />
    <ProjectReference Include="$(RepoRoot)src\HealthChecks\HealthChecks\src\Microsoft.Extensions.Diagnostics.HealthChecks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore.Tests" />
  </ItemGroup>
</Project>
