#pragma checksum "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "dd901a1308d91331879cabdc9f6c4666357d361c"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles.TestFiles_IntegrationTests_CodeGenerationIntegrationTest_Usings_Runtime), @"default", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml")]
namespace Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles
{
    #line hidden
#nullable restore
#line 1 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
using System.IO;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
using Foo = System.Text.Encoding;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
using System;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
using static System;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
using static System.Console;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
using static global::System.Text.Encoding;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"dd901a1308d91331879cabdc9f6c4666357d361c", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml")]
    public class TestFiles_IntegrationTests_CodeGenerationIntegrationTest_Usings_Runtime
    {
        #pragma warning disable 1998
        public async System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
            WriteLiteral("\r\n");
#nullable restore
#line 9 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
   
    using var disposable = (IDisposable)ViewData["disposable"];
    using System.IDisposable otherDisposable = (IDisposable)ViewData["otherdisposable"];

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<p>Path\'s full type name is ");
#nullable restore
#line 14 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
                       Write(typeof(Path).FullName);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n<p>Foo\'s actual full type name is ");
#nullable restore
#line 15 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
                             Write(typeof(Foo).FullName);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
