<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <OutputType>library</OutputType>
    <StaticWebAssetBasePath>_content/TestContentPackage</StaticWebAssetBasePath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(_SkipReferencedProjectPublishAssets)' == 'true'">
    <StaticWebAssetsGetPublishAssetsTargets>_SkipGetPublishAssetsForTrimmedBuild</StaticWebAssetsGetPublishAssetsTargets>
  </PropertyGroup>

  <!-- No-op target used to prevent the Static Web Assets SDK from redundantly re-publishing this project. -->
  <Target Name="_SkipGetPublishAssetsForTrimmedBuild" />

  <ItemGroup>
    <Reference Include="Microsoft.AspNetCore.Components" />
    <Reference Include="Microsoft.AspNetCore.Components.Authorization" />
    <Reference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>

</Project>
