// <auto-generated />
namespace Microsoft.AspNetCore.DataProtection.Abstractions
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Microsoft.AspNetCore.DataProtection.Abstractions.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        /// The payload was invalid.
        /// </summary>
        internal static string CryptCommon_PayloadInvalid
        {
            get => GetString("CryptCommon_PayloadInvalid");
        }

        /// <summary>
        /// The payload was invalid.
        /// </summary>
        internal static string FormatCryptCommon_PayloadInvalid()
            => GetString("CryptCommon_PayloadInvalid");

        /// <summary>
        /// The purposes collection cannot be null or empty and cannot contain null elements.
        /// </summary>
        internal static string DataProtectionExtensions_NullPurposesCollection
        {
            get => GetString("DataProtectionExtensions_NullPurposesCollection");
        }

        /// <summary>
        /// The purposes collection cannot be null or empty and cannot contain null elements.
        /// </summary>
        internal static string FormatDataProtectionExtensions_NullPurposesCollection()
            => GetString("DataProtectionExtensions_NullPurposesCollection");

        /// <summary>
        /// An error occurred during a cryptographic operation.
        /// </summary>
        internal static string CryptCommon_GenericError
        {
            get => GetString("CryptCommon_GenericError");
        }

        /// <summary>
        /// An error occurred during a cryptographic operation.
        /// </summary>
        internal static string FormatCryptCommon_GenericError()
            => GetString("CryptCommon_GenericError");

        /// <summary>
        /// No service for type '{0}' has been registered.
        /// </summary>
        internal static string DataProtectionExtensions_NoService
        {
            get => GetString("DataProtectionExtensions_NoService");
        }

        /// <summary>
        /// No service for type '{0}' has been registered.
        /// </summary>
        internal static string FormatDataProtectionExtensions_NoService(object p0)
            => string.Format(CultureInfo.CurrentCulture, GetString("DataProtectionExtensions_NoService"), p0);

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
