//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:N.N.NNNNN.N
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOutput {
using System;

public class MarkupInCodeBlock {
#line hidden
public MarkupInCodeBlock() {
}
public override void Execute() {

#line 1 "MarkupInCodeBlock.cshtml"
  
    for(int i = 1; i <= 10; i++) {


#line default
#line hidden
WriteLiteral("        <p>Hello from C#, #");


#line 3 "MarkupInCodeBlock.cshtml"
                       Write(i.ToString());


#line default
#line hidden
WriteLiteral("</p>\r\n");


#line 4 "MarkupInCodeBlock.cshtml"
    }


#line default
#line hidden
WriteLiteral("\r\n");

}
}
}
