// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using Microsoft.AspNetCore.Server.Kestrel.Internal.Http;
using Microsoft.Extensions.Primitives;
using Xunit;

namespace Microsoft.AspNetCore.Server.KestrelTests
{
    public class FrameHeadersTests
    {
        [Theory]
        [InlineData("keep-alive", ConnectionOptions.KeepAlive)]
        [InlineData("keep-alive, upgrade", ConnectionOptions.KeepAlive | ConnectionOptions.Upgrade)]
        [InlineData("keep-alive,upgrade", ConnectionOptions.KeepAlive | ConnectionOptions.Upgrade)]
        [InlineData("upgrade, keep-alive", ConnectionOptions.KeepAlive | ConnectionOptions.Upgrade)]
        [InlineData("upgrade,keep-alive", ConnectionOptions.KeepAlive | ConnectionOptions.Upgrade)]
        [InlineData("upgrade,,keep-alive", ConnectionOptions.KeepAlive | ConnectionOptions.Upgrade)]
        [InlineData("keep-alive,", ConnectionOptions.KeepAlive)]
        [InlineData("keep-alive,,", ConnectionOptions.KeepAlive)]
        [InlineData(",keep-alive", ConnectionOptions.KeepAlive)]
        [InlineData(",,keep-alive", ConnectionOptions.KeepAlive)]
        [InlineData("keep-alive, ", ConnectionOptions.KeepAlive)]
        [InlineData("keep-alive, ,", ConnectionOptions.KeepAlive)]
        [InlineData("keep-alive, , ", ConnectionOptions.KeepAlive)]
        [InlineData("keep-alive ,", ConnectionOptions.KeepAlive)]
        [InlineData(",keep-alive", ConnectionOptions.KeepAlive)]
        [InlineData(", keep-alive", ConnectionOptions.KeepAlive)]
        [InlineData(",,keep-alive", ConnectionOptions.KeepAlive)]
        [InlineData(", ,keep-alive", ConnectionOptions.KeepAlive)]
        [InlineData(",, keep-alive", ConnectionOptions.KeepAlive)]
        [InlineData(", , keep-alive", ConnectionOptions.KeepAlive)]
        [InlineData("upgrade,", ConnectionOptions.Upgrade)]
        [InlineData("upgrade,,", ConnectionOptions.Upgrade)]
        [InlineData(",upgrade", ConnectionOptions.Upgrade)]
        [InlineData(",,upgrade", ConnectionOptions.Upgrade)]
        [InlineData("upgrade, ", ConnectionOptions.Upgrade)]
        [InlineData("upgrade, ,", ConnectionOptions.Upgrade)]
        [InlineData("upgrade, , ", ConnectionOptions.Upgrade)]
        [InlineData("upgrade ,", ConnectionOptions.Upgrade)]
        [InlineData(",upgrade", ConnectionOptions.Upgrade)]
        [InlineData(", upgrade", ConnectionOptions.Upgrade)]
        [InlineData(",,upgrade", ConnectionOptions.Upgrade)]
        [InlineData(", ,upgrade", ConnectionOptions.Upgrade)]
        [InlineData(",, upgrade", ConnectionOptions.Upgrade)]
        [InlineData(", , upgrade", ConnectionOptions.Upgrade)]
        [InlineData("close,", ConnectionOptions.Close)]
        [InlineData("close,,", ConnectionOptions.Close)]
        [InlineData(",close", ConnectionOptions.Close)]
        [InlineData(",,close", ConnectionOptions.Close)]
        [InlineData("close, ", ConnectionOptions.Close)]
        [InlineData("close, ,", ConnectionOptions.Close)]
        [InlineData("close, , ", ConnectionOptions.Close)]
        [InlineData("close ,", ConnectionOptions.Close)]
        [InlineData(",close", ConnectionOptions.Close)]
        [InlineData(", close", ConnectionOptions.Close)]
        [InlineData(",,close", ConnectionOptions.Close)]
        [InlineData(", ,close", ConnectionOptions.Close)]
        [InlineData(",, close", ConnectionOptions.Close)]
        [InlineData(", , close", ConnectionOptions.Close)]
        [InlineData("kupgrade", ConnectionOptions.None)]
        [InlineData("keupgrade", ConnectionOptions.None)]
        [InlineData("ukeep-alive", ConnectionOptions.None)]
        [InlineData("upkeep-alive", ConnectionOptions.None)]
        [InlineData("k,upgrade", ConnectionOptions.Upgrade)]
        [InlineData("u,keep-alive", ConnectionOptions.KeepAlive)]
        [InlineData("ke,upgrade", ConnectionOptions.Upgrade)]
        [InlineData("up,keep-alive", ConnectionOptions.KeepAlive)]
        [InlineData("close", ConnectionOptions.Close)]
        [InlineData("upgrade,close", ConnectionOptions.Close | ConnectionOptions.Upgrade)]
        [InlineData("close,upgrade", ConnectionOptions.Close | ConnectionOptions.Upgrade)]
        [InlineData("keep-alive2", ConnectionOptions.None)]
        [InlineData("keep-alive2,", ConnectionOptions.None)]
        [InlineData("keep-alive2 ", ConnectionOptions.None)]
        [InlineData("keep-alive2 ,", ConnectionOptions.None)]
        [InlineData("keep-alive2,", ConnectionOptions.None)]
        [InlineData("upgrade2", ConnectionOptions.None)]
        [InlineData("upgrade2,", ConnectionOptions.None)]
        [InlineData("upgrade2 ", ConnectionOptions.None)]
        [InlineData("upgrade2 ,", ConnectionOptions.None)]
        [InlineData("upgrade2,", ConnectionOptions.None)]
        [InlineData("close2", ConnectionOptions.None)]
        [InlineData("close2,", ConnectionOptions.None)]
        [InlineData("close2 ", ConnectionOptions.None)]
        [InlineData("close2 ,", ConnectionOptions.None)]
        [InlineData("close2,", ConnectionOptions.None)]
        [InlineData("keep-alivekeep-alive", ConnectionOptions.None)]
        [InlineData("keep-aliveupgrade", ConnectionOptions.None)]
        [InlineData("upgradeupgrade", ConnectionOptions.None)]
        [InlineData("upgradekeep-alive", ConnectionOptions.None)]
        [InlineData("closeclose", ConnectionOptions.None)]
        [InlineData("closeupgrade", ConnectionOptions.None)]
        [InlineData("upgradeclose", ConnectionOptions.None)]
        [InlineData("keep-alive 2", ConnectionOptions.None)]
        [InlineData("upgrade 2", ConnectionOptions.None)]
        [InlineData("keep-alive 2, close", ConnectionOptions.Close)]
        [InlineData("upgrade 2, close", ConnectionOptions.Close)]
        [InlineData("close, keep-alive 2", ConnectionOptions.Close)]
        [InlineData("close, upgrade 2", ConnectionOptions.Close)]
        [InlineData("close 2, upgrade", ConnectionOptions.Upgrade)]
        [InlineData("upgrade, close 2", ConnectionOptions.Upgrade)]
        [InlineData("k2ep-alive", ConnectionOptions.None)]
        [InlineData("ke2p-alive", ConnectionOptions.None)]
        [InlineData("u2grade", ConnectionOptions.None)]
        [InlineData("up2rade", ConnectionOptions.None)]
        [InlineData("c2ose", ConnectionOptions.None)]
        [InlineData("cl2se", ConnectionOptions.None)]
        [InlineData("k2ep-alive,", ConnectionOptions.None)]
        [InlineData("ke2p-alive,", ConnectionOptions.None)]
        [InlineData("u2grade,", ConnectionOptions.None)]
        [InlineData("up2rade,", ConnectionOptions.None)]
        [InlineData("c2ose,", ConnectionOptions.None)]
        [InlineData("cl2se,", ConnectionOptions.None)]
        [InlineData("k2ep-alive ", ConnectionOptions.None)]
        [InlineData("ke2p-alive ", ConnectionOptions.None)]
        [InlineData("u2grade ", ConnectionOptions.None)]
        [InlineData("up2rade ", ConnectionOptions.None)]
        [InlineData("c2ose ", ConnectionOptions.None)]
        [InlineData("cl2se ", ConnectionOptions.None)]
        [InlineData("k2ep-alive ,", ConnectionOptions.None)]
        [InlineData("ke2p-alive ,", ConnectionOptions.None)]
        [InlineData("u2grade ,", ConnectionOptions.None)]
        [InlineData("up2rade ,", ConnectionOptions.None)]
        [InlineData("c2ose ,", ConnectionOptions.None)]
        [InlineData("cl2se ,", ConnectionOptions.None)]
        public void TestParseConnection(string connection, ConnectionOptions expectedConnectionOptionss)
        {
            var connectionOptions = FrameHeaders.ParseConnection(connection);
            Assert.Equal(expectedConnectionOptionss, connectionOptions);
        }

        [Theory]
        [InlineData("keep-alive", "upgrade", ConnectionOptions.KeepAlive | ConnectionOptions.Upgrade)]
        [InlineData("upgrade", "keep-alive", ConnectionOptions.KeepAlive | ConnectionOptions.Upgrade)]
        [InlineData("keep-alive", "", ConnectionOptions.KeepAlive)]
        [InlineData("", "keep-alive", ConnectionOptions.KeepAlive)]
        [InlineData("upgrade", "", ConnectionOptions.Upgrade)]
        [InlineData("", "upgrade", ConnectionOptions.Upgrade)]
        [InlineData("keep-alive, upgrade", "", ConnectionOptions.KeepAlive | ConnectionOptions.Upgrade)]
        [InlineData("upgrade, keep-alive", "", ConnectionOptions.KeepAlive | ConnectionOptions.Upgrade)]
        [InlineData("", "keep-alive, upgrade", ConnectionOptions.KeepAlive | ConnectionOptions.Upgrade)]
        [InlineData("", "upgrade, keep-alive", ConnectionOptions.KeepAlive | ConnectionOptions.Upgrade)]
        [InlineData("", "", ConnectionOptions.None)]
        [InlineData("close", "", ConnectionOptions.Close)]
        [InlineData("", "close", ConnectionOptions.Close)]
        [InlineData("close", "upgrade", ConnectionOptions.Close | ConnectionOptions.Upgrade)]
        [InlineData("upgrade", "close", ConnectionOptions.Close | ConnectionOptions.Upgrade)]
        public void TestParseConnectionMultipleValues(string value1, string value2, ConnectionOptions expectedConnectionOptionss)
        {
            var connection = new StringValues(new[] { value1, value2 });
            var connectionOptions = FrameHeaders.ParseConnection(connection);
            Assert.Equal(expectedConnectionOptionss, connectionOptions);
        }
    }
}
