@{
    IncludeRules=@('PSAvoidUsingCmdletAliases',
                   'PSAvoidUsingWMICmdlet',
                   'PSAvoidUsingPositionalParameters',
                   'PSAvoidUsingInvokeExpression',
                   'PSUseDeclaredVarsMoreThanAssignments',
                   'PSUseCmdletCorrectly',
                   'PSStandardDSCFunctionsInResource',
                   'PSUseIdenticalMandatoryParametersForDSC',
                   'PSUseIdenticalParametersForDSC')
}