// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace Microsoft.AspNetCore.Server.Kestrel.Core;

internal enum ConnectionEndReason
{
    Unset,
    OtherError,
    ConnectionReset,
    FlowControlWindowExceeded,
    KeepAliveTimeout,
    InsufficientTlsVersion,
    InvalidHandshake,
    InvalidStreamId,
    FrameAfterStreamClose,
    UnknownStream,
    UnsupportedFrame,
    UnexpectedFrame,
    InvalidFrameLength,
    InvalidDataPadding,
    InvalidRequestHeaders,
    InvalidRequestLine,
    StreamResetLimitExceeded,
    WindowUpdateSizeInvalid,
    StreamSelfDependency,
    InvalidSettings,
    MissingStreamEnd,
    MaxFrameLengthExceeded,
    ErrorReadingHeaders,
    ErrorWritingHeaders,
    InvalidHttpVersion,
    RequestHeadersTimeout,
    MinRequestBodyDataRate,
    MinResponseDataRate,
    FlowControlQueueSizeExceeded,
    OutputQueueSizeExceeded,
    ClosedCriticalStream,
    AbortedByApp,
    WriteCanceled,
    BodyReaderInvalidState,
    ServerTimeout,
    StreamCreationError,
    IOError,
    ClientGoAway,
    AppShutdownTimeout,
    GracefulAppShutdown,
    TransportCompleted,
    TlsHandshakeFailed,
    TlsOverHttp,
    MaxRequestBodySizeExceeded,
    UnexpectedEndOfRequestContent,
    MaxConcurrentConnectionsExceeded,
    ResponseContentLengthMismatch,
    RequestNoKeepAlive,
    ResponseNoKeepAlive,
    ErrorAfterStartingResponse
}
