<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(BundledNETCoreAppTargetFramework)</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!-- Need to build this project in source build -->
    <ExcludeFromSourceOnlyBuild>false</ExcludeFromSourceOnlyBuild>
    <!-- No need to track public APIs of these MSBuild tasks. -->
    <AddPublicApiAnalyzers>false</AddPublicApiAnalyzers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="$(MicrosoftBuildUtilitiesCoreVersion)" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(SharedSourceRoot)CertificateGeneration\**\*.cs" LinkBase="shared\CertificateGeneration" />
  </ItemGroup>

</Project>
