// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
    public partial class TestComponent : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line (1,2)-(1,15) 24 "x:\dir\subdir\Test\TestComponent.cshtml"
__builder.AddContent(0, RenderPerson((__builder2) => {
    __builder2.AddMarkupContent(1, "<div>HI</div>");
}
));

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
#nullable restore
#line 2 "x:\dir\subdir\Test\TestComponent.cshtml"
       
    object RenderPerson(RenderFragment p) => null;

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
