<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Support for storing keys using Entity Framework Core.</Description>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageTags>aspnetcore;dataprotection;entityframeworkcore</PackageTags>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />

    <ProjectReference Include="$(RepoRoot)src\DataProtection\DataProtection\src\Microsoft.AspNetCore.DataProtection.csproj" />
  </ItemGroup>

</Project>
