<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Tests for users to verify their own implementations of SignalR types</Description>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <IsPackable>true</IsPackable>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(SignalRSharedSourceRoot)DuplexPipe.cs" Link="DuplexPipe.cs" />
    <Compile Include="$(SignalRSharedSourceRoot)MemoryBufferWriter.cs" Link="Internal\MemoryBufferWriter.cs" />
    <Compile Include="..\..\..\common\testassets\Tests.Utils\HubConnectionContextUtils.cs" Link="HubConnectionContextUtils.cs" />
    <Compile Include="..\..\..\common\testassets\Tests.Utils\TaskExtensions.cs" Link="TaskExtensions.cs" />
    <Compile Include="..\..\..\common\testassets\Tests.Utils\TestClient.cs" Link="TestClient.cs" />
    <Compile Include="$(SharedSourceRoot)TaskExtensions.cs" LinkBase="Shared\TaskExtensions.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.assert" />
    <PackageReference Include="xunit.extensibility.core" />

    <ProjectReference Include="$(RepoRoot)src\Http\Routing.Abstractions\src\Microsoft.AspNetCore.Routing.Abstractions.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Http\Routing\src\Microsoft.AspNetCore.Routing.csproj" />
    <ProjectReference Include="$(RepoRoot)src\SignalR\common\Protocols.Json\src\Microsoft.AspNetCore.SignalR.Protocols.Json.csproj" />
    <ProjectReference Include="$(RepoRoot)src\SignalR\common\Protocols.MessagePack\src\Microsoft.AspNetCore.SignalR.Protocols.MessagePack.csproj" />
    <ProjectReference Include="$(RepoRoot)src\SignalR\common\Protocols.NewtonsoftJson\src\Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson.csproj" />
    <ProjectReference Include="$(RepoRoot)src\SignalR\common\SignalR.Common\src\Microsoft.AspNetCore.SignalR.Common.csproj" />
    <ProjectReference Include="$(RepoRoot)src\SignalR\server\Core\src\Microsoft.AspNetCore.SignalR.Core.csproj" />
  </ItemGroup>

</Project>
