<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>
      ASP.NET Core MVC view rendering features. Contains common types used in most MVC applications as well as view rendering features such as view engines, views, view components, and HTML helpers.
      Commonly used types:
      Microsoft.AspNetCore.Mvc.Controller
      Microsoft.AspNetCore.Mvc.ValidateAntiForgeryTokenAttribute
      Microsoft.AspNetCore.Mvc.ViewComponent
    </Description>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageTags>aspnetcore;aspnetcoremvc</PackageTags>
    <IsAspNetCoreApp>true</IsAspNetCoreApp>
    <IsPackable>false</IsPackable>
    <Nullable>disable</Nullable>
    <DefineConstants>$(DefineConstants);MVC_VIEWFEATURES</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)src\DataProtection\Extensions\src\Microsoft.AspNetCore.DataProtection.Extensions.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Mvc\Mvc.Core\src\Microsoft.AspNetCore.Mvc.Core.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Mvc\Mvc.DataAnnotations\src\Microsoft.AspNetCore.Mvc.DataAnnotations.csproj" />

    <ProjectReference Include="$(RepoRoot)src\Antiforgery\src\Microsoft.AspNetCore.Antiforgery.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Components\Endpoints\src\Microsoft.AspNetCore.Components.Endpoints.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Html.Abstractions\src\Microsoft.AspNetCore.Html.Abstractions.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Http\Headers\src\Microsoft.Net.Http.Headers.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Http\Http.Abstractions\src\Microsoft.AspNetCore.Http.Abstractions.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Http\Http.Features\src\Microsoft.AspNetCore.Http.Features.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Http\Http\src\Microsoft.AspNetCore.Http.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Http\Routing.Abstractions\src\Microsoft.AspNetCore.Routing.Abstractions.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Http\Routing\src\Microsoft.AspNetCore.Routing.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Http\WebUtilities\src\Microsoft.AspNetCore.WebUtilities.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Middleware\Diagnostics.Abstractions\src\Microsoft.AspNetCore.Diagnostics.Abstractions.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Middleware\Diagnostics\src\Microsoft.AspNetCore.Diagnostics.csproj" />
    <ProjectReference Include="$(RepoRoot)src\Mvc\Mvc.Abstractions\src\Microsoft.AspNetCore.Mvc.Abstractions.csproj" />
    <ProjectReference Include="$(RepoRoot)src\StaticAssets\src\Microsoft.AspNetCore.StaticAssets.csproj" />
    <ProjectReference Include="$(RepoRoot)src\WebEncoders\src\Microsoft.Extensions.WebEncoders.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(SharedSourceRoot)\AntiforgeryMetadata.cs" LinkBase="Infrastructure" />
    <Compile Include="$(SharedSourceRoot)MiddlewareInvokedKeys.cs" LinkBase="Infrastructure" />
    <Compile Include="$(SharedSourceRoot)SafeHttpMethods.cs" LinkBase="Infrastructure" />
    <Compile Include="$(SharedSourceRoot)\PooledArrayBufferWriter.cs" LinkBase="Infrastructure" />
    <Compile Include="$(SharedSourceRoot)\Components\ResourceCollectionResolver.cs" LinkBase="Infrastructure" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Microsoft.AspNetCore.Mvc" />
    <InternalsVisibleTo Include="Microsoft.AspNetCore.Mvc.Razor" />
    <InternalsVisibleTo Include="Microsoft.AspNetCore.Mvc.RazorPages" />
    <InternalsVisibleTo Include="Microsoft.AspNetCore.Mvc.TagHelpers" />
    <InternalsVisibleTo Include="Microsoft.AspNetCore.Mvc.Test" />
    <InternalsVisibleTo Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson.Test" />
    <InternalsVisibleTo Include="Microsoft.AspNetCore.Mvc.Razor.Test" />
    <InternalsVisibleTo Include="Microsoft.AspNetCore.Mvc.RazorPages.Test" />
    <InternalsVisibleTo Include="Microsoft.AspNetCore.Mvc.TagHelpers.Test" />
    <InternalsVisibleTo Include="Microsoft.AspNetCore.Mvc.Views.TestCommon" />
    <InternalsVisibleTo Include="Microsoft.AspNetCore.Mvc.ViewFeatures.Test" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" Key="$(MoqPublicKey)" />
  </ItemGroup>
</Project>
