//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34006
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNet.StaticFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNet.StaticFiles.Resources", System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(Resources)).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IContentTypeProvider was specified..
        /// </summary>
        internal static string Args_NoContentTypeProvider {
            get {
                return ResourceManager.GetString("Args_NoContentTypeProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No formatter provided..
        /// </summary>
        internal static string Args_NoFormatter {
            get {
                return ResourceManager.GetString("Args_NoFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server does not support the sendfile.SendAsync extension..
        /// </summary>
        internal static string Exception_SendFileNotSupported {
            get {
                return ResourceManager.GetString("Exception_SendFileNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index of.
        /// </summary>
        internal static string HtmlDir_IndexOf {
            get {
                return ResourceManager.GetString("HtmlDir_IndexOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        internal static string HtmlDir_LastModified {
            get {
                return ResourceManager.GetString("HtmlDir_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string HtmlDir_Modified {
            get {
                return ResourceManager.GetString("HtmlDir_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string HtmlDir_Name {
            get {
                return ResourceManager.GetString("HtmlDir_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string HtmlDir_Size {
            get {
                return ResourceManager.GetString("HtmlDir_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of files in the given directory.  Column headers are listed in the first row..
        /// </summary>
        internal static string HtmlDir_TableSummary {
            get {
                return ResourceManager.GetString("HtmlDir_TableSummary", resourceCulture);
            }
        }
    }
}
