<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <OutputType>Exe</OutputType>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TieredCompilation>false</TieredCompilation>
    <DefineConstants>$(DefineConstants);IS_BENCHMARKS</DefineConstants>
    <SkipMicrobenchmarksValidation>true</SkipMicrobenchmarksValidation>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include=".\Proto\chat.proto" GrpcServices="Server" />
    <Protobuf Include=".\Proto\greet.proto" GrpcServices="Client" />

    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />

    <ProjectReference Include="$(RepoRoot)src\Grpc\JsonTranscoding\src\Microsoft.AspNetCore.Grpc.JsonTranscoding\Microsoft.AspNetCore.Grpc.JsonTranscoding.csproj" />

    <Compile Include="$(SharedSourceRoot)BenchmarkRunner\*.cs" />
  </ItemGroup>
</Project>
