// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
    public partial class TestComponent : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<Test.User>(0);
            __builder.AddAttribute(1, "Name", 
#nullable restore
#line 1 "x:\dir\subdir\Test\TestComponent.cshtml"
                   UserName

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(2, "NameChanged", Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => UserName = __value, UserName));
            __builder.AddAttribute(3, "IsActive", 
#nullable restore
#line 1 "x:\dir\subdir\Test\TestComponent.cshtml"
                                              UserIsActive

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(4, "IsActiveChanged", Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => UserIsActive = __value, UserIsActive));
            __builder.CloseComponent();
        }
        #pragma warning restore 1998
#nullable restore
#line 3 "x:\dir\subdir\Test\TestComponent.cshtml"
       
    public string UserName { get; set; }
    public bool UserIsActive { get; set; }

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
