trigger:
- master
- release/*

# See https://github.com/aspnet/BuildTools
resources:
  repositories:
  - repository: buildtools
    type: github
    endpoint: DotNet-Bot GitHub Connection
    name: aspnet/BuildTools
    ref: refs/heads/master

phases:
- template: .vsts-pipelines/templates/phases/default-build.yml@buildtools
  parameters:
    agentOs: Windows
    beforeBuild:
    - script: sqllocaldb start
      displayName: Start LocalDB

- template: .vsts-pipelines/templates/phases/default-build.yml@buildtools
  parameters:
    agentOs: macOS

- template: .vsts-pipelines/templates/phases/default-build.yml@buildtools
  parameters:
    agentOs: Linux
